### ISSUE TITLE
Cubical memory error

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#1085]
I am getting a memory error on the ray machine during the cubical run.

INFO      23:02:06 - data_handler       [0.9/0.9 6.3/6.3 0.0Gb]   generated 24 row chunks based on time and DDID
INFO      23:02:06 - data_handler       [0.9/0.9 6.3/6.3 0.0Gb]   row chunks yield 24 potential tiles
INFO      23:02:06 - data_handler       [1.0/1.0 6.4/6.5 0.0Gb]   coarsening this to 6 tiles (max 4 chunks per tile, based on 99/4 requested)
INFO      23:02:07 - wisdom             [1.0/1.0 6.4/6.5 0.0Gb] Detected a total of 503.81GiB of system memory.
INFO      23:02:07 - wisdom             [1.0/1.0 6.4/6.5 0.0Gb] Per-solver (worker) memory use estimated at 381.81GiB: 75.78% of total system memory.
INFO      23:02:07 - wisdom             [1.0/1.0 6.4/6.5 0.0Gb] Peak I/O memory use estimated at 552.19GiB: 109.60% of total system memory.
INFO      23:02:07 - wisdom             [1.0/1.0 6.4/6.5 0.0Gb] Total peak memory usage estimated at 38351.10GiB: 7612.16% of total system memory.
INFO      23:02:07 - main               [1.0/1.0 6.4/6.5 0.0Gb] Exiting with exception: MemoryError(Estimated memory usage exceeds total system memory. Memory usage can be reduced by lowering the number of chunks, the dimensions of each chunk or the number of worker processes. This error can suppressed by unsetting --dist-safe.)
 Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cubical/main.py", line 536, in main
    estimate_mem(ms, tile_list, GD["data"], GD["dist"])
  File "/usr/local/lib/python3.6/dist-packages/cubical/data_handler/wisdom.py", line 89, in estimate_mem
    "Estimated memory usage exceeds total system memory. Memory usage "
MemoryError: Estimated memory usage exceeds total system memory. Memory usage can be reduced by lowering the number of chunks, the dimensions of each chunk or the number of worker processes. This error can suppressed by unsetting --dist-safe.

Warning: setupterm: could not find terminal
Traceback (most recent call last):
  File "/stimela_mount/code/run.py", line 57, in <module>
    subprocess.check_call(shlex.split(_runc))
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gocubical', '--sol-jones', 'G', '--data-ms', '/stimela_mount/msdir/field2_fixvis-Abell3376East_corr.ms', '--data-column', 'DATA', '--data-time-chunk', '360', '--data-freq-chunk', '0', '--model-list', 'MODEL_DATA', '--model-ddes', 'never', '--montblanc-dtype', 'float', '--weight-column', 'WEIGHT', '--flags-apply', '-cubical', '--madmax-enable', '1', '--madmax-estimate', 'corr', '--madmax-plot', '1', '--madmax-threshold', '0,10', '--sel-diag', '0', '--sol-term-iters', '5,0', '--bbc-save-to', '/stimela_mount/output/continuum/selfcal_products/bbc-gains-1-field2_fixvis-Abell3376East_corr.parmdb', '--dist-ncpu', '100', '--dist-max-chunks', '4', '--out-name', '/stimela_mount/output/continuum/selfcal_products/mypipelinerun_field2_fixvis-Abell3376East_corr_1_cubical', '--out-overwrite', '1', '--out-mode', 'sc', '--out-casa-gaintables', '1', '--out-plots', '1', '--dist-nworker', '0', '--log-memory', '1', '--log-boring', '1', '--g-time-int', '120', '--g-freq-int', '0', '--g-clip-low', '0.5', '--g-clip-high', '2.0', '--g-solvable', '1', '--g-type', 'phase-diag', '--g-save-to', '/stimela_mount/output/continuum/selfcal_products/mypipelinerun-g-phase-gains-1-field2_fixvis-Abell3376East_corr.parmdb', '--g-update-type', 'phase-diag', '--g-max-prior-error', '0.1', '--g-max-post-error', '0.1', '--degridding-OverS', '11', '--degridding-Support', '7', '--degridding-Nw', '100', '--degridding-wmax', '0', '--degridding-Padding', '1.7', '--degridding-NDegridBand', '16', '--degridding-MaxFacetSize', '0.25', '--degridding-MinNFacetPerAxis', '1']' returned non-zero exit status 1.
singularity returns error code 1
job failed at 2020-05-10 01:02:07.665343 after 0:00:25.140694
Traceback (most recent call last):
  File "/home/vparekh/Stimela/stimela/recipe.py", line 572, in run
    job.run_job()
  File "/home/vparekh/Stimela/stimela/recipe.py", line 302, in run_job
    self.job.run()
  File "/home/vparekh/Stimela/stimela/singularity.py", line 120, in run
    logfile=self.logfile)
  File "/home/vparekh/Stimela/stimela/utils/xrun_poll.py", line 187, in xrun
    raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
stimela.utils.StimelaCabRuntimeError: singularity returns error code 1

**Comment by o-smirnov** [comment]
Could you please attach your Caracal config file.

**Comment by viralp** [comment]
[log-self_cal-calibrate-cubical-field0-iter1-20200508-113254.txt](https://github.com/caracal-pipeline/caracal/files/4615614/log-self_cal-calibrate-cubical-field0-iter1-20200508-113254.txt)

**Comment by o-smirnov** [comment]
Ah yes, beat me to it, log file is even better. But also give us your current ``.yml`` config please.

(@caracal-pipeline/admins, should we not set up issue reporting templates where we always ask people to include the config and the logfile?)

**Comment by viralp** [comment]
[test.txt](https://github.com/caracal-pipeline/caracal/files/4620931/test.txt)

**Comment by o-smirnov** [comment]
```
self_cal:
 ncpu: 12
 cal_timeslots_chunk: 360
```
Those aren't defaults (and actually these are old parameter names), and they're set way too high. Memory use goes proportional to the product of those two. Try using the defaults and see how the memory use goes.

**Comment by paoloserra** [comment]
@viralp note that you can use `cal_timeslots_chunk: -1` to set it to the smallest useful chunk size = the largest time solution interval `gsols_timeslots` in your pipeline run. See https://caracal.readthedocs.io/en/latest/manual/workers/selfcal/index.html#cal-timeslots-chunk . That should be the most conservative setting.

I'm not sure whether we have a sensible default for `ncpu`. This really depends on the machine. The current default is 5, see https://caracal.readthedocs.io/en/latest/manual/workers/selfcal/index.html#ncpu , but that is unlikely to be good for all or even most cases.

Anyway, as pointed out by @o-smirnov , your configuration file seems to include outdated parameter names compared to our 1.0.0 release. Please get that CARACal version (or master) before trying again. Parameter names will be more stable now that we have a release out, so you shouldn't have to do this very often in the future.

**Comment by o-smirnov** [comment]
I think this is explained, but feel free to reopen if you have more problems @viralp.

(See also #1017).

**Comment by viralp** [comment]
The error is still persistent (on ray machine) with a smaller value of ```cal_timeslots_chunk``` (120 and 60 both giving the error)

```
INFO      05:16:54 - main               [0.9/0.9 4.2/4.2 0.0Gb] Exiting with exception: MemoryError(Estimated memory usage exceeds total system memory. Memory usage can be reduced by lowering the number of chunks, the dimensions of each chunk or the number of worker processes. This error can suppressed by unsetting --dist-safe.)
 Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cubical/main.py", line 536, in main
    estimate_mem(ms, tile_list, GD["data"], GD["dist"])
  File "/usr/local/lib/python3.6/dist-packages/cubical/data_handler/wisdom.py", line 89, in estimate_mem
    "Estimated memory usage exceeds total system memory. Memory usage "
MemoryError: Estimated memory usage exceeds total system memory. Memory usage can be reduced by lowering the number of chunks, the dimensions of each chunk or the number of worker processes. This error can suppressed by unsetting --dist-safe.

```
I upgraded the Caracal and config file to ``schema_version: 1.0.0```

```
selfcal:
  enable: true
  ncpu: 12
  img_npix: 6000
  img_cell: 1.5
  img_niter: 1000000
  img_nchans: 8
  img_robust: 0.0
  cal_niter: 3
  cal_timeslots_chunk: 120
  start_iter: 1
  img_specfit_nrcoeff: 2
  img_multiscale: false
  img_multiscale_scales: [10,20,30]
  image:
    enable: true
    cleanmask_thr: [20,10,5,3]
    clean_cutoff: [0.5,0.5,0.5,0.5]
    col: [DATA,CORRECTED_DATA,CORRECTED_DATA,CORRECTED_DATA]
  calibrate:
    enable: true
    model: ['1','2','3']
    gain_matrix_type: ['GainDiagPhase', 'GainDiagPhase', 'GainDiagPhase']
    gsols_chan: [0, 0, 0]
    gsols_timeslots: [120, 60, 30]
  transfer_apply_gains:
     enable: false
  transfer_model:
     enable: false
  report: true
```

**Comment by paoloserra** [comment]
Could you consider smaller values for gsols_timeslots (having set `cal_timeslots_chunk: -1`)? If this is MeerKAT, you're probably starting with a solution interval of 8 sec x 120 = 16 min, which seems rather long.

Also, have you averaged your data in frequency with the `transform` worker before running the `selfcal` worker? That will also decrease the memory usage.

**Comment by viralp** [comment]
@paoloserra I also tried ```gsols_timeslots``` starts with 60 (and chunk size = -1), but the same error. I averaged 5 channels of the data in the ```transform``` worker.

**Comment by NiankunYu** [comment]
Hello, I met with the same problem. But most parameters are just set as the default values, so I don't know how to fix it. The pipeline can run until the step of selfcal, I have tried different settings, but never finished this part. It is the problem of memory... 
Here are my details:

1. installation type (e.g., Docker, Singularity)
Singularity

2. software version (both CARACal and Stimela)
(caracal_venv) nyu@mcn16:/diske/nyu/meerkat2025/data_process/output/logs-20250813-093042$ caracal --version
/diske/nyu/caracal/caracal_testdir/caracal_venv/lib/python3.11/site-packages/caracal/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
caracal version 1.1.5
(caracal_venv) nyu@mcn16:/diske/nyu/meerkat2025/data_process/output/logs-20250813-093042$ stimela --version
/diske/nyu/caracal/caracal_testdir/caracal_venv/lib/python3.11/site-packages/stimela/__init__.py:5: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
stimela version 1.7.10
(caracal_venv) nyu@mcn16:/diske/nyu/meerkat2025/data_process/output/logs-20250813-093042$ uname -a
Linux mcn16 5.10.0-32-amd64 #1 SMP Debian 5.10.223-1 (2024-08-10) x86_64 GNU/Linux
(caracal_venv) nyu@mcn16:/diske/nyu/meerkat2025/data_process/output/logs-20250813-093042$ singularity --version
apptainer version 1.3.6

3. CARACal configuration file

[config.txt](https://github.com/user-attachments/files/21757548/config.txt)

4. CARACal log files.
[log-caracal.txt](https://github.com/user-attachments/files/21757531/log-caracal.txt)

[log-selfcal-calibrate-cubical-field0-iter1-20250813-093042.txt](https://github.com/user-attachments/files/21757534/log-selfcal-calibrate-cubical-field0-iter1-20250813-093042.txt)

Many thanks for your help. I also turn to similar github pages here, but nearly all my parameters are default. So I do not know how to fix it exactly.

**Comment by NiankunYu** [comment]
Hi [Athanaseus](https://github.com/Athanaseus), many thanks. It is running now. I will let you know if it works.

**Comment by NiankunYu** [comment]
Hi [Athanaseus](https://github.com/Athanaseus), 

It did make progress here. But I doubt if the selfcal process has been finished properly. Moreover, the line function certainly failed. After running for two days, it shows problems between selfcal and line. So maybe there are still some problems with the config file? 

The attached files are the log files. I think I am almost there with your help. Many thanks. 

[log-caracal.txt](https://github.com/user-attachments/files/21801849/log-caracal.txt)
[log-line-modelsub-ms0-20250814-095111.txt](https://github.com/user-attachments/files/21801847/log-line-modelsub-ms0-20250814-095111.txt)
[log-selfcal-save-mypipelinerun_selfcal_after-ms0-20250814-095111.txt](https://github.com/user-attachments/files/21801848/log-selfcal-save-mypipelinerun_selfcal_after-ms0-20250814-095111.txt)

**Comment by Athanaseus** [comment]
Hi @NiankunYu ,

It appears `selfcal` completed successfully.
```
# Writing /stimela_mount/output/continuum/image_3/mypipelinerun_NGC1533_3-MFS-psf.fits...
# Writing /stimela_mount/output/continuum/image_3/mypipelinerun_NGC1533_3-MFS-dirty.fits...
# Writing /stimela_mount/output/continuum/image_3/mypipelinerun_NGC1533_3-MFS-residual.fits...
# Writing /stimela_mount/output/continuum/image_3/mypipelinerun_NGC1533_3-MFS-model.fits...
# Rendering sources to restored image (beam=18.61''-43.79'', PA=-153.42 deg)... DONE
# Writing /stimela_mount/output/continuum/image_3/mypipelinerun_NGC1533_3-MFS-image.fits...
# Writing changed model back to /stimela_mount/msdir/1739209274-sdp-l0_2025-06-04T15-22-10_XKR-NGC1533-corr.ms:
#  0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
# Cleaning up temporary files...
2025-08-15 18:33:43 CARACal.Stimela.image-field0-iter3 DEBUG: The /usr/local/bin/apptainer run --workdir /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17551578814765527 --contain  --bind /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17551578814765527/stimela_parameter_files/image_field0_iter3-13978696133073617552250569745207.json:/stimela_mount/configfile:ro --bind /diske/nyu/caracal/caracal_testdir/caracal_venv/lib/python3.11/site-packages/stimela/cargo/cab/wsclean/src:/stimela_mount/code:ro --bind /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17551578814765527/passwd:/etc/passwd:rw --bind /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17551578814765527/group:/etc/group:rw --bind /diske/nyu/caracal/caracal_testdir/caracal_venv/bin/stimela_runscript:/singularity:ro --bind /mcn_data5/nyu/meerkat2025/data_process/msdir:/stimela_mount/msdir:rw --bind /mcn_data5/nyu/meerkat2025/data_process/input:/stimela_mount/input:ro --bind /mcn_data5/nyu/meerkat2025/data_process/output:/stimela_mount/output:rw --bind /mcn_data5/nyu/meerkat2025/data_process/output/tmp:/stimela_mount/output/tmp:rw /mcn_data5/nyu/meerkat2025/data_process/stimela_wsclean_1.7.7.sif /singularity process has exited
2025-08-15 18:33:43 CARACal.Stimela.image-field0-iter3 INFO: job complete at 2025-08-15 18:33:43.766584 after 4:52:49.542149
2025-08-15 18:33:43 CARACal.Stimela.selfcal INFO: Saving pipeline information in .last_selfcal.json
2025-08-15 18:33:43 CARACal.Stimela.selfcal INFO: Recipe executed successfully
2025-08-15 18:33:43 CARACal INFO: Number of iterations to be done: 2
```

You could check the final images from `selfcal` here and see if they look alright:
`output/continuum/image_3/`


It looks like the pipeline was `killed` just as it started Line worker (just before subtracting model):
```
2025-08-15 18:35:27 CARACal.Stimela.line INFO: STEP 1 :: modelsub-ms0:: Subtract model column
2025-08-15 18:35:27 CARACal.Stimela INFO: Validating parameters for cab msutils (stimela/msutils:1.4.6)
2025-08-15 18:35:27 CARACal.Stimela DEBUG: Validating parameter command
2025-08-15 18:35:27 CARACal.Stimela DEBUG: Validating parameter subtract
2025-08-15 18:35:27 CARACal.Stimela DEBUG: Validating parameter col1
2025-08-15 18:35:27 CARACal.Stimela DEBUG: Validating parameter col2
2025-08-15 18:35:27 CARACal.Stimela DEBUG: Validating parameter column
2025-08-15 18:35:27 CARACal.Stimela INFO: Parameters validated and saved to /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17552757179090679/stimela_parameter_files/modelsub_ms0-13978686553720017552757265777695.json
2025-08-15 18:35:27 CARACal.Stimela.modelsub-ms0 INFO: Starting container [716]. Timeout set to -1. The container ID is printed below.
# running /usr/local/bin/apptainer run --workdir /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17552757179090679 --contain  --bind /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17552757179090679/stimela_parameter_files/modelsub_ms0-13978686553720017552757265777695.json:/stimela_mount/configfile:ro --bind /diske/nyu/caracal/caracal_testdir/caracal_venv/lib/python3.11/site-packages/stimela/cargo/cab/msutils/src:/stimela_mount/code:ro --bind /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17552757179090679/passwd:/etc/passwd:rw --bind /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17552757179090679/group:/etc/group:rw --bind /diske/nyu/caracal/caracal_testdir/caracal_venv/bin/stimela_runscript:/singularity:ro --bind /mcn_data5/nyu/meerkat2025/data_process/msdir:/stimela_mount/msdir:rw --bind /mcn_data5/nyu/meerkat2025/data_process/input:/stimela_mount/input:ro --bind /mcn_data5/nyu/meerkat2025/data_process/output:/stimela_mount/output:rw --bind /mcn_data5/nyu/meerkat2025/data_process/output/tmp:/stimela_mount/output/tmp:rw /mcn_data5/nyu/meerkat2025/data_process/stimela_msutils_1.4.6.sif /singularity
# Killed
2025-08-15 18:41:43 CARACal.Stimela.modelsub-ms0 DEBUG: The /usr/local/bin/apptainer run --workdir /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17552757179090679 --contain  --bind /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17552757179090679/stimela_parameter_files/modelsub_ms0-13978686553720017552757265777695.json:/stimela_mount/configfile:ro --bind /diske/nyu/caracal/caracal_testdir/caracal_venv/lib/python3.11/site-packages/stimela/cargo/cab/msutils/src:/stimela_mount/code:ro --bind /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17552757179090679/passwd:/etc/passwd:rw --bind /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17552757179090679/group:/etc/group:rw --bind /diske/nyu/caracal/caracal_testdir/caracal_venv/bin/stimela_runscript:/singularity:ro --bind /mcn_data5/nyu/meerkat2025/data_process/msdir:/stimela_mount/msdir:rw --bind /mcn_data5/nyu/meerkat2025/data_process/input:/stimela_mount/input:ro --bind /mcn_data5/nyu/meerkat2025/data_process/output:/stimela_mount/output:rw --bind /mcn_data5/nyu/meerkat2025/data_process/output/tmp:/stimela_mount/output/tmp:rw /mcn_data5/nyu/meerkat2025/data_process/stimela_msutils_1.4.6.sif /singularity process has exited
2025-08-15 18:41:43 CARACal.Stimela.modelsub-ms0 ERROR: /usr/local/bin/apptainer run --workdir /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17552757179090679 --contain returns error code 1
2025-08-15 18:41:43 CARACal.Stimela.modelsub-ms0 ERROR: job failed at 2025-08-15 18:41:43.794194 after 0:06:16.082194
2025-08-15 18:41:43 CARACal.Stimela.modelsub-ms0 ERROR: Traceback (most recent call last):
2025-08-15 18:41:43 CARACal.Stimela.modelsub-ms0 ERROR:   File "/diske/nyu/caracal/caracal_testdir/caracal_venv/lib/python3.11/site-packages/stimela/recipe.py", line 713, in run
2025-08-15 18:41:43 CARACal.Stimela.modelsub-ms0 ERROR:     job.run_job()
2025-08-15 18:41:43 CARACal.Stimela.modelsub-ms0 ERROR:   File "/diske/nyu/caracal/caracal_testdir/caracal_venv/lib/python3.11/site-packages/stimela/recipe.py", line 425, in run_job
2025-08-15 18:41:43 CARACal.Stimela.modelsub-ms0 ERROR:     self.job.run(output_wrangler=self.apply_output_wranglers)
2025-08-15 18:41:43 CARACal.Stimela.modelsub-ms0 ERROR:   File "/diske/nyu/caracal/caracal_testdir/caracal_venv/lib/python3.11/site-packages/stimela/singularity.py", line 128, in run
2025-08-15 18:41:43 CARACal.Stimela.modelsub-ms0 ERROR:     utils.xrun(f"{BINARY} run --workdir {self.execdir} --contain",
2025-08-15 18:41:43 CARACal.Stimela.modelsub-ms0 ERROR:   File "/diske/nyu/caracal/caracal_testdir/caracal_venv/lib/python3.11/site-packages/stimela/utils/xrun_poll.py", line 227, in xrun
2025-08-15 18:41:43 CARACal.Stimela.modelsub-ms0 ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2025-08-15 18:41:43 CARACal.Stimela.modelsub-ms0 ERROR: stimela.utils.StimelaCabRuntimeError: /usr/local/bin/apptainer run --workdir /mcn_data5/nyu/meerkat2025/data_process/.stimela_workdir-17552757179090679 --contain returns error code 1
```

You could try re-running from the line worker (`-sw line`) and see if this happens again:
`/diske/nyu/caracal/caracal_testdir/caracal_venv/bin/caracal --start-worker line -debug -ct singularity -c config.yml`

Best regards
