### ISSUE TITLE
Installation error on Ilifu

### ISSUE THREAD

**Issue by ianjarog** [caracal-pipeline/caracal#1087]
I just tried to install the latest version of Caracal on Ilifu (pip install -U caracal) and got the following errors after pulling images. caracal installation succeeded but stimela image pulling failed

singularity = 3.5.2
stimela = 1.5.1 

(caracal-venv-phissc) ianja@slwrk-103:/scratch/users/ianja/caracal_phisscc$ stimela pull -s
Traceback (most recent call last):
  File "/scratch/users/ianja/caracal_phisscc/caracal-venv-phissc/bin/stimela", line 14, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/scratch/users/ianja/caracal_phisscc/caracal-venv-phissc/lib/python3.7/site-packages/stimela/main.py", line 592, in main
    _cmd(argv)
  File "/scratch/users/ianja/caracal_phisscc/caracal-venv-phissc/lib/python3.7/site-packages/stimela/main.py", line 269, in pull
    log = logger.StimelaLogger(LOG_FILE, jtype=jtype)
  File "/scratch/users/ianja/caracal_phisscc/caracal-venv-phissc/lib/python3.7/site-packages/stimela/utils/logger.py", line 27, in __init__
    if self.info.get(item, None) is None:
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by KshitijT** [comment]
@ianjarog , could you please try running the pipeline without stimela pull and let us know if you get the same error?

**Comment by KshitijT** [comment]
P.S. `stimela pull -s` seems to work fine for me on ILIFU.

**Comment by o-smirnov** [comment]
@SpheMakh look at this please.

**Comment by gigjozsa** [comment]
@ianjarog is this working now?

**Comment by gigjozsa** [comment]
@ianjarog is this working now?

**Comment by ianjarog** [comment]
@gigjozsa  @SpheMakh  stimela pull -s still gives me the following error 

(caracal-june) ianja@slwrk-132:/scratch/users/ianja$ stimela pull -s
Traceback (most recent call last):
  File "/scratch/users/ianja/caracal-june/bin/stimela", line 14, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/scratch/users/ianja/caracal-june/lib/python3.7/site-packages/stimela/main.py", line 601, in main
    _cmd(argv)
  File "/scratch/users/ianja/caracal-june/lib/python3.7/site-packages/stimela/main.py", line 270, in pull
    log = logger.StimelaLogger(LOG_FILE, jtype=jtype)
  File "/scratch/users/ianja/caracal-june/lib/python3.7/site-packages/stimela/utils/logger.py", line 27, in __init__
    if self.info.get(item, None) is None:
AttributeError: 'NoneType' object has no attribute 'get'

Running it without pull as @SpheMakh  suggested gave me the following errors: 

2020-06-21 14:49:15 STIMELA.obsconf INFO: Config directory cannot be found. Will create /scratch/users/ianja/.stimela_workdir-15927437555030944/stimela_parameter_files
2020-06-21 14:49:15 CARACal INFO: obsconf: initializing
# running cd /scratch/users/ianja && singularity pull  --name stimela_casa_1.2.6.sif docker://stimela/casa:1.2.6
# time="2020-06-21T14:49:15+02:00" level=warning msg="\"/run/user/10176\" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR.: stat /run/user/10176: no such file or directory: Trying to pull image in the event that it is a public image."
# FATAL:   While making image from oci registry: while opening destination file: open /scratch/users/ianja/caracal-june-images/stimela_casa_1.2.6.sif: no such file or directory
2020-06-21 14:49:19 CARACal ERROR: cd /scratch/users/ianja && singularity returns error code 255 [StimelaCabRuntimeError]
2020-06-21 14:49:19 CARACal INFO:   More information can be found in the logfile at output/logs-20200621-144843/log-caracal.txt
2020-06-21 14:49:19 CARACal INFO: exiting with error code 1

**Comment by KshitijT** [comment]
@ianjarog , if you are running this on ILIFU, you don't need to pull the images, they are stored in:  `/software/astro/caracal/STIMELA_IMAGES_1.6.1`

You can run your pipeline with `caracal -c configfile.yml  -ct singularity -sid /software/astro/caracal/STIMELA_IMAGES_1.6.1 .

If you haven't updated your caracal installation, I would suggest bringing it upto the latest version.

**Comment by ianjarog** [comment]
@KshitijT  Looks like it's working using your solution...I will wait for it to go through though and will close this. Thanks

**Comment by ianjarog** [comment]
@KshitijT I am getting another error but not installation issue anymore I think..Not sure if I should still post this here..This is on crosscal...I am testing the new caracal. 

# INFO:    Build complete: /users/ianja/.radiopadre/osmirnov_radiopadre:1.0.singularity.img.new.img
2020-06-21 15:51:02 CARACal INFO: Rendered report output/mypipelinerun-detailed-final-report.html
2020-06-21 15:51:02 CARACal INFO: crosscal: initializing
2020-06-21 15:51:02 CARACal INFO: Obtaining divine knowledge from: /scratch/users/ianja/caracal-june/lib/python3.7/site-packages/caracal/data/casa_calibrators.txt
2020-06-21 15:54:12 CARACal ERROR: cd /software/astro/caracal/STIMELA_IMAGES_1.6.1 && singularity returns error code 255 [StimelaCabRuntimeError]
2020-06-21 15:54:12 CARACal INFO:   More information can be found in the logfile at output/logs-20200621-151107/log-caracal.txt
2020-06-21 15:54:12 CARACal INFO:   You are running version 1.0.3
2020-06-21 15:54:12 CARACal ERROR: Traceback (most recent call last):
2020-06-21 15:54:12 CARACal ERROR:   File "/scratch/users/ianja/caracal-june/lib/python3.7/site-packages/caracal/main.py", line 184, in __run
2020-06-21 15:54:12 CARACal ERROR:     pipeline.run_workers()
2020-06-21 15:54:12 CARACal ERROR:   File "/scratch/users/ianja/caracal-june/lib/python3.7/site-packages/caracal/workers/worker_administrator.py", line 357, in run_workers
2020-06-21 15:54:12 CARACal ERROR:     worker.worker(self, recipe, config)
2020-06-21 15:54:12 CARACal ERROR:   File "/scratch/users/ianja/caracal-june/lib/python3.7/site-packages/caracal/workers/crosscal_worker.py", line 572, in worker
2020-06-21 15:54:12 CARACal ERROR:     prefix, label=label, ftype="primary")
2020-06-21 15:54:12 CARACal ERROR:   File "/scratch/users/ianja/caracal-june/lib/python3.7/site-packages/caracal/workers/crosscal_worker.py", line 312, in solve
2020-06-21 15:54:12 CARACal ERROR:     do_KGBF(i)
2020-06-21 15:54:12 CARACal ERROR:   File "/scratch/users/ianja/caracal-june/lib/python3.7/site-packages/caracal/workers/crosscal_worker.py", line 200, in do_KGBF
2020-06-21 15:54:12 CARACal ERROR:     plotgains(recipe, pipeline, field_id, caltable, iobs, term=term)
2020-06-21 15:54:12 CARACal ERROR:   File "/scratch/users/ianja/caracal-june/lib/python3.7/site-packages/caracal/workers/crosscal_worker.py", line 337, in plotgains
2020-06-21 15:54:12 CARACal ERROR:     label='{0:s}:: Plot gaincal phase'.format(step))
2020-06-21 15:54:12 CARACal ERROR:   File "/scratch/users/ianja/caracal-june/lib/python3.7/site-packages/stimela/recipe.py", line 591, in add
2020-06-21 15:54:12 CARACal ERROR:     singularity_image_dir=self.singularity_image_dir)
2020-06-21 15:54:12 CARACal ERROR:   File "/scratch/users/ianja/caracal-june/lib/python3.7/site-packages/stimela/recipe.py", line 292, in setup_job
2020-06-21 15:54:12 CARACal ERROR:     os.path.basename(cont.image), directory=singularity_image_dir)
2020-06-21 15:54:12 CARACal ERROR:   File "/scratch/users/ianja/caracal-june/lib/python3.7/site-packages/stimela/singularity.py", line 49, in pull
2020-06-21 15:54:12 CARACal ERROR:     name, fp])
2020-06-21 15:54:12 CARACal ERROR:   File "/scratch/users/ianja/caracal-june/lib/python3.7/site-packages/stimela/utils/xrun_poll.py", line 189, in xrun
2020-06-21 15:54:12 CARACal ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2020-06-21 15:54:12 CARACal ERROR: stimela.utils.StimelaCabRuntimeError: cd /software/astro/caracal/STIMELA_IMAGES_1.6.1 && singularity returns error code 255
2020-06-21 15:54:12 CARACal INFO: exiting with error code 1

**Comment by KshitijT** [comment]
Yeah, not sure what is happening here. Could you please paste your configuration file crosscal section here?

**Comment by ianjarog** [comment]
@KshitijT  I am just using the default for now 
crosscal:
  enable: true
  label_in: cal
  apply_cal:
    applyto:
      - gcal
      - bpcal
  report: true

**Comment by KshitijT** [comment]
Ok, let me check it out.

**Comment by SpheMakh** [comment]
@ianjarog could you please post the log-caracal.txt file

**Comment by ianjarog** [comment]
@SpheMakh  

[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/4809864/log-caracal.txt)

**Comment by KshitijT** [comment]
FYI, the same crosscal config goes through fine for me.

**Comment by SpheMakh** [comment]
@ianjarog can you try using the master version of stimela?

**Comment by ianjarog** [comment]
@SpheMakh  I get another error using now 
pip install git+git://github.com/sphemakh/Stimela

[Uploading log-caracal.txt…]()

**Comment by ianjarog** [comment]
@SpheMakh I get another error using now
pip install git+git://github.com/sphemakh/Stimela 
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/4810073/log-caracal.txt)

**Comment by KshitijT** [comment]
> @SpheMakh I get another error using now
> pip install git+git://github.com/sphemakh/Stimela
> [log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/4810073/log-caracal.txt)

That's probably because the images there are not for stimela master version? Please run without the `-sid /soft/....` part.

**Comment by ianjarog** [comment]
> > @SpheMakh I get another error using now
> > pip install git+git://github.com/sphemakh/Stimela
> > [log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/4810073/log-caracal.txt)
> 
> That's probably because the images there are not for stimela master version? Please run without the `-sid /soft/....` part.

@SpheMakh  But if I leave it out then it cannot find the images. [my stimela pull -s did not work as well]
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/4810250/log-caracal.txt)

**Comment by KshitijT** [comment]
> > > @SpheMakh I get another error using now
> > > pip install git+git://github.com/sphemakh/Stimela
> > > [log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/4810073/log-caracal.txt)
> > 
> > 
> > That's probably because the images there are not for stimela master version? Please run without the `-sid /soft/....` part.
> 
> @SpheMakh But if I leave it out then it cannot find the images. [my stimela pull -s did not work as well]
> [log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/4810250/log-caracal.txt)

Ah, it's a bit flattering to be confused with @SpheMakh , but the suggestion was by @KshitijT . ;)

The error you are getting might be because there is no SINGULARITY_PULLFOLDER variable defined in your .bashrc file (let us know if that's not the case). If that's the case, could you please (only for the purposes of this test) define: 
```
export SINGULARITY_PULLFOLDER=/scratch/users/putyourusernamehere/STIMELA_IMAGES_NEW

```
source it and then run as `caracal -c configfile.yml -sid /scratch/users/putyourusernamehere/STIMELA_IMAGES_NEW/` .

That should sort it out, I think. We definitely need an advisory of sorts for running CARACal on ILIFU, I'll add one.

**Comment by ianjarog** [comment]
> > > > @SpheMakh I get another error using now
> > > > pip install git+git://github.com/sphemakh/Stimela
> > > > [log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/4810073/log-caracal.txt)
> > > 
> > > 
> > > That's probably because the images there are not for stimela master version? Please run without the `-sid /soft/....` part.
> > 
> > 
> > @SpheMakh But if I leave it out then it cannot find the images. [my stimela pull -s did not work as well]
> > [log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/4810250/log-caracal.txt)
> 
> Ah, it's a bit flattering to be confused with @SpheMakh , but the suggestion was by @KshitijT . ;)
> 
> The error you are getting might be because there is no SINGULARITY_PULLFOLDER variable defined in your .bashrc file (let us know if that's not the case). If that's the case, could you please (only for the purposes of this test) define:
> 
> ```
> export SINGULARITY_PULLFOLDER=/scratch/users/putyourusernamehere/STIMELA_IMAGES_NEW
> ```
> 
> source it and then run as `caracal -c configfile.yml -sid /scratch/users/putyourusernamehere/STIMELA_IMAGES_NEW/` .
> 
> That should sort it out, I think. We definitely need an advisory of sorts for running CARACal on ILIFU, I'll add one.

@KshitijT  Sorry for the confusion ;) Is this using the stimela master branch? Also my problem is that I do not know where the singularity images are located without pulling them?? you told earlier that they are located in /software/astro/caracal/STIMELA_IMAGES_1.6.1 but then I got issues using it...

**Comment by KshitijT** [comment]
> Is this using the stimela master branch?

Yes.

>  Also my problem is that I do not know where the singularity images are located without pulling them??

They should be pulled automatically as long as the stimela pullfolder you define is empty.
