### ISSUE TITLE
ddcal error 

### ISSUE THREAD

**Issue by bnamumba** [caracal-pipeline/caracal#1105]
2020-05-15 11:26:02 CARACal INFO: obsconf: running
2020-05-15 11:26:02 CARACal.Stimela.obsconf INFO: Saving pipeline information in .last_obsconf.json
2020-05-15 11:26:02 CARACal.Stimela.obsconf INFO: Recipe executed successfully
2020-05-15 11:26:02 CARACal INFO: obsconf: finished
2020-05-15 11:26:02 CARACal.Stimela.ddcal INFO: ---------------------------------
2020-05-15 11:26:02 CARACal.Stimela.ddcal INFO: Stimela version 1.4.6
2020-05-15 11:26:02 CARACal.Stimela.ddcal INFO: Sphesihle Makhathini <sphemakh@gmail.com>
2020-05-15 11:26:02 CARACal.Stimela.ddcal INFO: Running: ddcal
2020-05-15 11:26:02 CARACal.Stimela.ddcal INFO: ---------------------------------
2020-05-15 11:26:02 CARACal INFO: ddcal: initializing
2020-05-15 11:26:02 CARACal ERROR: '' [KeyError]
2020-05-15 11:26:02 CARACal INFO:   More information can be found in the logfile at output/logs-20200515-112423/log-caracal.txt
2020-05-15 11:26:02 CARACal INFO:   You are running version 1.0.0
2020-05-15 11:26:02 CARACal ERROR: Traceback (most recent call last):
2020-05-15 11:26:02 CARACal ERROR:   File "/scratch/users/brenda/latest/venv/lib/python3.7/site-packages/caracal/main.py", line 184, in __run
2020-05-15 11:26:02 CARACal ERROR:     pipeline.run_workers()
2020-05-15 11:26:02 CARACal ERROR:   File "/scratch/users/brenda/latest/venv/lib/python3.7/site-packages/caracal/workers/worker_administrator.py", line 324, in run_workers
2020-05-15 11:26:02 CARACal ERROR:     worker.worker(self, recipe, config)
2020-05-15 11:26:02 CARACal ERROR:   File "/scratch/users/brenda/latest/venv/lib/python3.7/site-packages/caracal/workers/ddcal_worker.py", line 429, in worker
2020-05-15 11:26:02 CARACal ERROR:     mslist = ms_dict[target]
2020-05-15 11:26:02 CARACal ERROR: KeyError: ''
2020-05-15 11:26:02 CARACal INFO: exiting with error code 1

**Comment by KshitijT** [comment]
@bnamumba , please copy your configuration (the ddcal section) here?

**Comment by bnamumba** [comment]
basically used default settings..

ddcal:
  enable: true
  label_in: 'corr'
  use_pb: true
  calibrate_dd:
    enable: True
    de_sources_mode: manual
  copy_data:
    enable: true
  image_wsclean:
    enable: true
  transfer_model_dd:
    enable: true

**Comment by KshitijT** [comment]
Right, you need to specify the coordinates of the schema manually, since you have set the de_sources_mode to 'manual'.

**Comment by bnamumba** [comment]
Thanks. I will auto first then specify the coordinates and try again.

**Comment by KshitijT** [comment]
Closing this issue. @bnamumba , please reopen if needed.
