### ISSUE TITLE
Empty flag:flag_mask:uvrange causes a crash

### ISSUE THREAD

**Issue by healytwin1** [caracal-pipeline/caracal#1137]
Using the default meerkat RFI mask (with default parameters), I get the following error:
```
# running cd /scratch/users/juliahealy/fullband/.stimela_workdir-1590307581646135 && singularity run --workdir /scratch/users/juliahealy/fullband/.stimela_workdir-1590307581646135 --containall  --bind /scratch/users/juliahealy/fullband/.stimela_workdir-1590307581646135/stimela_parameter_files/flag_mask_ms0-13997835199940815903075825160935.json:/stimela_mount/configfile:ro --bind /scratch/users/juliahealy/cenv1/lib/python3.7/site-packages/stimela/cargo/cab/rfimasker/src:/stimela_mount/code:ro --bind /scratch/users/juliahealy/fullband/.stimela_workdir-1590307581646135/passwd:/etc/passwd:rw --bind /scratch/users/juliahealy/fullband/.stimela_workdir-1590307581646135/group:/etc/group:rw --bind /scratch/users/juliahealy/cenv1/bin/stimela_runscript:/singularity:ro --bind /scratch/users/juliahealy/fullband/msdir:/stimela_mount/msdir:rw --bind /scratch/users/juliahealy/fullband/input:/stimela_mount/input:ro --bind /scratch/users/juliahealy/fullband/output:/stimela_mount/output:rw --bind /scratch/users/juliahealy/fullband/output/tmp:/stimela_mount/output/tmp:rw /idia/projects/healy-a2626/stimela/stimela_rfimasker_1.2.0.sif /singularity
# 2020-05-24 08:10:38,668:      RFI Masker
# 2020-05-24 08:10:38,668:      Version 1.0.1
# 2020-05-24 08:10:38,668:      Module installed at /usr/local/bin
# 2020-05-24 08:10:38,668:      ----------------------------------------
# usage: mask_ms.py [-h] -m MASK [--accumulation_mode {or,override}]
#                   [--spwid SPWID [SPWID ...]] [--dilate DILATE]
#                   [--uvrange UVRANGE] [-s] [--memory MEMORY] [--simulate]
#                   ms [ms ...]
# mask_ms.py: error: argument --uvrange: invalid _casa_style_range value: '/stimela_mount/msdir/1563407160_sdp_l0.ms'
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 35, in <module>
#     subprocess.check_call(shlex.split(_runc))
#   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['mask_ms.py', '--mask', '/stimela_mount/input/labelled_rfimask.pickle.npy', '--accumulation_mode', 'or', '--memory', '4096', '--uvrange', '/stimela_mount/msdir/1563407160_sdp_l0.ms']' returned non-zero exit status 2
2020-05-24 10:10:38 STIMELA.flag INFO: Completed jobs : ['version-Epoch1_v1_flag_before-ms0', 'flag-autocorr-ms0', 'flag-shadow-ms0']
2020-05-24 10:10:38 STIMELA.flag INFO: Remaining jobs : ['flag-rfi-ms0', 'flag-summary-ms0']
2020-05-24 10:10:38 STIMELA.flag INFO: Logging remaining task: flag-rfi-ms0:: AOFlagger auto-flagging flagging pass ms=1563407160_sdp_l0.ms fields=J2253+1608,J1939-6342
2020-05-24 10:10:38 STIMELA.flag INFO: Logging remaining task: flag-summary-ms0:: Flagging summary  ms=1563407160_sdp_l0.ms
2020-05-24 10:10:38 STIMELA.flag INFO: Saving pipeline information in .last_flag.json
```

I am running caracal v1.0.1 (developer version).

**Comment by o-smirnov** [comment]
Did you specify a uvrange for the mask? It looks like it's being passed an empty string, and getting confused about that.

(Guys, any way to trap this intelligently?)

**Comment by healytwin1** [comment]
No, my understanding is that if you left the uvrange empty it will select everything?

**Comment by o-smirnov** [comment]
Ah I see, so that's the bug. Empty uvrange not being treated properly. I've renamed the bug.

Setting it to ``0~8km`` should work around the problem for now.

(Personally, I use 0~1000m or even 0~500m... that's a pretty big mask, and the longer baselines are usually ok without it...)

**Comment by healytwin1** [comment]
So using '0~8km' crashed, but '0~1000' did not.

**Comment by o-smirnov** [comment]
Ah maybe it doesn't take units.... ``0~8000`` would work I suppose...

**Comment by bennahugo** [comment]
Note that the task is deprecated. Use tricolour instead the mask can be
applied by itself as a strategy.

It does not take an empty string. If you specify uvrange you have to
specify a valid range

**Comment by o-smirnov** [comment]
> It does not take an empty string. If you specify uvrange you have to specify a valid range

Exactly what the problem was. Caracal was passing it an empty string instead of omitting uvrange entirely.
