### ISSUE TITLE
sunblocker: "IndexError: string index out of range"

### ISSUE THREAD

**Issue by HaoChen-ast** [caracal-pipeline/caracal#1177]
I have 9 target fields in my ms file.
It always report an error when running `sunblocker` for the third target field.
No issue to run `sunblocker` for 1 field.

log:
> 2020-06-14 22:12:17 CARACal ERROR: string index out of range [IndexError]
> 2020-06-14 22:12:17 CARACal INFO:   More information can be found in the logfile at output/logs-20200614-215557/log-caracal.txt
> 2020-06-14 22:12:17 CARACal INFO:   You are running version 1.0.0
> 2020-06-14 22:12:18 CARACal ERROR: Traceback (most recent call last):
> 2020-06-14 22:12:18 CARACal ERROR:   File "/idia/projects/vela/CARACal_all/CARACal-18May2020/CARACal-venv-18May2020/lib/python3.7/site-packages/caracal/main.py", line 184, in __run
> 2020-06-14 22:12:18 CARACal ERROR:     pipeline.run_workers()
> 2020-06-14 22:12:18 CARACal ERROR:   File "/idia/projects/vela/CARACal_all/CARACal-18May2020/CARACal-venv-18May2020/lib/python3.7/site-packages/caracal/workers/worker_administrator.py", line 324, in run_workers
> 2020-06-14 22:12:18 CARACal ERROR:     worker.worker(self, recipe, config)
> 2020-06-14 22:12:18 CARACal ERROR:   File "/idia/projects/vela/CARACal_all/CARACal-18May2020/CARACal-venv-18May2020/lib/python3.7/site-packages/caracal/workers/line_worker.py", line 544, in worker
> 2020-06-14 22:12:18 CARACal ERROR:     prefix = pipeline.prefix[i]
> 2020-06-14 22:12:18 CARACal ERROR: IndexError: string index out of range
> 2020-06-14 22:12:18 CARACal INFO: exiting with error code 1

It seems there some issue here:
https://github.com/caracal-pipeline/caracal/blob/49dd321f72b1cb17c9e34c4ff4981df692b7e0f9/caracal/workers/line_worker.py#L544

**Comment by KshitijT** [comment]
@HaoChen-ast , could you please share your config file and the log file?

**Comment by HaoChen-ast** [comment]
config file:
https://raw.githubusercontent.com/HaoChen-ast/test/master/1_V0_1547413577.yml

log file:
https://raw.githubusercontent.com/HaoChen-ast/test/master/log-caracal.txt

Thanks.

**Comment by HaoChen-ast** [comment]
I confirmed the error is here:
https://github.com/caracal-pipeline/caracal/blob/49dd321f72b1cb17c9e34c4ff4981df692b7e0f9/caracal/workers/line_worker.py#L544

My prefix in my config file is 'V0' (prefix: V0).
With sunblocker I got:
griddedvis_V.sunblocker.svg
griddedvis_0.sunblocker.svg

`pipeline.prefix[0]` here is 'V' of my prefix 'V0'
`pipeline.prefix[1]` here is '0' of my prefix 'V0'
Then, pipeline reports an error that no `pipeline.prefix[3]` (IndexError: string index out of range).
But I have 9 target fields, need to go to `pipeline.prefix[8]`.

I think `pipeline.prefix[i]` does not work as expected.
Please fix it.

Now, I set `prefix = pipeline.prefix` to let the pipeline work.
But in this condition, I can not get plot for all the 9 fields.
I can only get griddedvis_V0.sunblocker.svg for the last run field.

**Comment by KshitijT** [comment]
@gigjozsa is this fixed now? Can we close this issue?
