### ISSUE TITLE
Cannot find summary file in split line reduction strategy

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1189]
I am first doing a contsub and mstransform in line worker 1, then imaging in line worker 2. A summary of the config file
[ic1459_4-00-ic1459_4_a.yml.txt](https://github.com/caracal-pipeline/caracal/files/4862859/ic1459_4-00-ic1459_4_a.yml.txt):

```
line:
  enable: true
  label_in: 'l'
  restfreq: '1.420405752GHz'
  subtractmodelcol:
    enable: true
  make_cube:
    enable: false
  mstransform: 
    enable: true
    uvlin:
      enable: true
  pb_cube:
    enable: false
  freq_to_vel:
    enable: false
  remove_stokes_axis:
    enable: false
  sofia:
    enable: false

line__t20_r0:
  enable: true
  label_in: 'l'
  line_name: HI_t20_r0
  restfreq: '1.420405752GHz'
  subtractmodelcol:
    enable: false
  make_cube:
    enable: true
...
  mstransform: 
    enable: false
  flag_mst_errors:
     enable: false
  pb_cube:
    enable: true
  freq_to_vel:
    enable: true
  remove_stokes_axis:
    enable: true
  sofia:
    enable: true
```

This used to work before the Jihad. Now I get:
```
2020-07-02 05:57:18 CARACal ERROR: MS summary file ic1459_30MHz-J2256_3633-l_mst-summary.json not found at expected location. This is a bug or a misconfiguration. Was the MS transformed properly? [RuntimeError]
2020-07-02 05:57:18 CARACal INFO:   More information can be found in the logfile at output/logs-20200701-231745/log-caracal.txt
2020-07-02 05:57:18 CARACal INFO:   You are running version 1.1.0
2020-07-02 05:57:18 CARACal ERROR: Traceback (most recent call last):
2020-07-02 05:57:18 CARACal ERROR:   File "/scratch2/jozsa/ic1459/datared/caracal_venv/lib/python3.6/site-packages/caracal/main.py", line 184, in __run
2020-07-02 05:57:18 CARACal ERROR:     pipeline.run_workers()
2020-07-02 05:57:18 CARACal ERROR:   File "/scratch2/jozsa/ic1459/datared/caracal_venv/lib/python3.6/site-packages/caracal/workers/worker_administrator.py", line 391, in run_workers
2020-07-02 05:57:18 CARACal ERROR:     worker.worker(self, recipe, config)
2020-07-02 05:57:18 CARACal ERROR:   File "/scratch2/jozsa/ic1459/datared/caracal_venv/lib/python3.6/site-packages/caracal/workers/line_worker.py", line 596, in worker
2020-07-02 05:57:18 CARACal ERROR:     msinfo = pipeline.get_msinfo(f"{msbase}_mst{ext}")
2020-07-02 05:57:18 CARACal ERROR:   File "/scratch2/jozsa/ic1459/datared/caracal_venv/lib/python3.6/site-packages/caracal/workers/worker_administrator.py", line 177, in get_msinfo
2020-07-02 05:57:18 CARACal ERROR:     raise RuntimeError(f"MS summary file {msinfo_file} not found at expected location. This is a bug or "
2020-07-02 05:57:18 CARACal ERROR: RuntimeError: MS summary file ic1459_30MHz-J2256_3633-l_mst-summary.json not found at expected location. This is a bug or a misconfiguration. Was the MS transformed properly?
2020-07-02 05:57:18 CARACal INFO: exiting with error code 1
```
Unfortunately I cannot reproduce this now because of the next error. I any case I am not sure if this is a bug or a feature, hoping for feature...

Relevant summary files:
[ic1459_4-00-sysinfo.txt](https://github.com/caracal-pipeline/caracal/files/4862866/ic1459_4-00-sysinfo.txt)
[ic1459_4-00-ic1459_4_a-log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/4862868/ic1459_4-00-ic1459_4_a-log-caracal.txt)
[ic1459_4-00-ic1459_4_a.yml.txt](https://github.com/caracal-pipeline/caracal/files/4862870/ic1459_4-00-ic1459_4_a.yml.txt)
[ic1459_4-00.sh.txt](https://github.com/caracal-pipeline/caracal/files/4862871/ic1459_4-00.sh.txt)

**Comment by o-smirnov** [comment]
Gimme a few minutes, I think I know where to look.

**Comment by o-smirnov** [comment]
Try with the ``issue-1189`` branch. It was a cut-and-paste error during the jihad. (You know the holy books are full of them, right?)

**Comment by o-smirnov** [comment]
The nice part is, you're reproducing https://github.com/caracal-pipeline/caracal/issues/1112 which @PeterKamphuis couldn't, so save that config for me please...

**Comment by o-smirnov** [comment]
Well, I mean you have saved it already (above), thanks!

**Comment by gigjozsa** [comment]
For the holy records.

**Comment by gigjozsa** [comment]
Trying out issue-1189 now.

**Comment by gigjozsa** [comment]
That seems to work. @o-smirnov I will now rerun this from scratch using issue-1189, to make sure that there is nothing twisted.
