### ISSUE TITLE
Running caracal piece-wise in R/O mode leads to an MS not found error

### ISSUE THREAD

**Issue by gigjozsa** [caracal-pipeline/caracal#1190]
While trying to debug #1189 I encountered another bug or feature. I used the same config file as in #1189 but I disabled all workers before the culprit from #1189 (a line worker), see this config file
[this config file](https://github.com/caracal-pipeline/caracal/files/4862917/ic1459_4-01-ic1459_4_b.yml.txt). I got:
```
2020-07-02 10:10:59 CARACal.Stimela.getdata INFO: Config directory cannot be found. Will create /scratch2/jozsa/ic1459/datared/ic1459_4/.stimela_workdir-15936774594392009/stimela_parameter_files
2020-07-02 10:10:59 CARACal INFO: getdata: initializing
2020-07-02 10:10:59 CARACal ERROR: No MS files matching any of ['ic1459_30MHz'] were found at /scratch2/jozsa/ic1459/datared/ic1459_4/msdir. Please make sure that general: msdir , getdata: dataid, and (optionally) general: rawdatadir are set properly. [RuntimeError]
2020-07-02 10:10:59 CARACal INFO:   More information can be found in the logfile at output/logs-20200702-101058/log-caracal.txt
2020-07-02 10:10:59 CARACal INFO:   You are running version 1.1.0
2020-07-02 10:10:59 CARACal ERROR: Traceback (most recent call last):
2020-07-02 10:10:59 CARACal ERROR:   File "/scratch2/jozsa/ic1459/datared/caracal_venv/lib/python3.6/site-packages/caracal/main.py", line 184, in __run
2020-07-02 10:10:59 CARACal ERROR:     pipeline.run_workers()
2020-07-02 10:10:59 CARACal ERROR:   File "/scratch2/jozsa/ic1459/datared/caracal_venv/lib/python3.6/site-packages/caracal/workers/worker_administrator.py", line 391, in run_workers
2020-07-02 10:10:59 CARACal ERROR:     worker.worker(self, recipe, config)
2020-07-02 10:10:59 CARACal ERROR:   File "/scratch2/jozsa/ic1459/datared/caracal_venv/lib/python3.6/site-packages/caracal/workers/getdata_worker.py", line 18, in worker
2020-07-02 10:10:59 CARACal ERROR:     raise RuntimeError(f'No MS files matching any of {pipeline.dataid} were found at {pipeline.rawdatadir}. '\
2020-07-02 10:10:59 CARACal ERROR: RuntimeError: No MS files matching any of ['ic1459_30MHz'] were found at /scratch2/jozsa/ic1459/datared/ic1459_4/msdir. Please make sure that general: msdir , getdata: dataid, and (optionally) general: rawdatadir are set properly.
2020-07-02 10:10:59 CARACal INFO: exiting with error code 1
```
Again, after running caracal once, and it bombed out at worker ``line__t20_r0``, see #1189 , I tried to disable all other workers before and did not encounter the same error but the one described above.

Bug or feature?

Relevant info files:
[ic1459_4-01-sysinfo.txt](https://github.com/caracal-pipeline/caracal/files/4862928/ic1459_4-01-sysinfo.txt)
[ic1459_4-01-ic1459_4_b-log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/4862929/ic1459_4-01-ic1459_4_b-log-caracal.txt)
[ic1459_4-01-ic1459_4_b.yml.txt](https://github.com/caracal-pipeline/caracal/files/4862930/ic1459_4-01-ic1459_4_b.yml.txt)
[ic1459_4-01.sh.txt](https://github.com/caracal-pipeline/caracal/files/4862931/ic1459_4-01.sh.txt)

**Comment by gigjozsa** [comment]
The error goes away after copying the original raw data set into msdir (which obviously defeats teh purpose) and removing rawdatadir from general. Not sure if the two are connected, but I will now try to investigate #1189  a bit further.

**Comment by gigjozsa** [comment]
@o-smirnov @SpheMakh I think this might be a general concern for the R/O workflow. Re-starting the workflow or piece-wise data reduction seems not to work.

**Comment by o-smirnov** [comment]
Which box are you on?

**Comment by gigjozsa** [comment]
this is on com04

**Comment by o-smirnov** [comment]
Well ``/scratch2/jozsa/ic1459/datared/ic1459_4/msdir`` doesn't exist...

**Comment by gigjozsa** [comment]
Sorry, com06, sorry.

**Comment by o-smirnov** [comment]
Can I sudo as you and run it as you quickly? Which directory are you running it in?

**Comment by gigjozsa** [comment]
Sure, ``/scratch2/jozsa/ic1459/datared/ic1459_4``, see [ic1459_4-01.sh.txt](https://github.com/caracal-pipeline/caracal/files/4862931/ic1459_4-01.sh.txt) above. But I am currently testing the issue-1189 branch, see #1189  . Will stop when I'm past #1189 and hand over. But make sure to also edit the config file ``/scratch2/jozsa/ic1459/datared/ic1459_4_b.yml`` to again show ``rawdatadir: '/scratch2/jozsa/ic1459/rawdata'`` and delete ``ic1459_30MHz.ms`` from ``msdir`` (but please not from ``/scratch2/jozsa/ic1459/rawdata``).

**Comment by o-smirnov** [comment]
That sounds very twisted @gigjozsa, a typical Josh workflow. :P That description made my mind blank.

Are you sure you didn't just run it with your MS no longer in the rawdatadir? Because then it doesn't work -- the first thing the pipeline looks for are the original MSs under rawdatadir (even if you start it at a later worker and it doesn't actually touch them).

**Comment by gigjozsa** [comment]
Nope, @o-smirnov , I am very sure that the data are in rawdatadir. The workflow got twisted because of the bugs. For now let me rerun, and then try again to provoke the error. #1189 seems to be solved in your patch.

**Comment by o-smirnov** [comment]
OK. So I'm not doing anything about this issue until you confirm or deny.

**Comment by paoloserra** [comment]
@gigjozsa I've tried my best but could not reproduce this error. (I'm on branch issue-1189.)

Running CARACal up to `selfcal` (included) and immediately after that starting CARACal from `line` leads to no such error.

I've also tried with a run that stops at `line: mstransform` (included) followed by one that resumes from `line: make_cube`. Again no error.

All this is in R/O mode, where the original, input .MS lives in rawdatadir and does not exist inside msdir.

Please let us know whether this is still a problem for you.

**Comment by gigjozsa** [comment]
I am testing this right now.

**Comment by gigjozsa** [comment]
I cannot reproduce it any more either. Let's keep this open just for a while, though. I bet my leg this occurred.

**Comment by o-smirnov** [comment]
I'll bet a toe this occurred when you moved the ms from rawdatadir to msdir...

**Comment by gigjozsa** [comment]
You can start limping now.

**Comment by gigjozsa** [comment]
But we can trade it for a Jägermeister

**Comment by gigjozsa** [comment]
No, seriously, I copied the ms across after the error, to see if that would "solve" it.

**Comment by gigjozsa** [comment]
But it's a bit academical I admit.

**Comment by o-smirnov** [comment]
> But it's a bit academical I admit.

Bet you won't be saying that when we show up for next busy week you sans leg and me sans toe...

**Comment by KshitijT** [comment]
> > But it's a bit academical I admit.
> 
> Bet you won't be saying that when we show up for next busy week you sans leg and me sans toe...

I'll make sure I am in the opposite team for our football match..

**Comment by o-smirnov** [comment]
Let's discuss this in #1199.
