### ISSUE TITLE
"IndexError: list index out of range" when scan intents are not populated

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1203]
I have an MS where the scan intents are not set, so obsconf is unable to set calibrators etc. automatically. It trundles along until crosscal, which fails with:

```
2020-07-15 16:10:31 CARACal ERROR: list index out of range [IndexError]
2020-07-15 16:10:31 CARACal INFO:   More information can be found in the logfile at output/logs-20200715-154616/log-caracal.txt
2020-07-15 16:10:31 CARACal INFO:   You are running version v1.0.3-106-ge6b22320
2020-07-15 16:10:31 CARACal ERROR: Traceback (most recent call last):
2020-07-15 16:10:31 CARACal ERROR:   File "/home/oms/projects/caracal/caracal/main.py", line 184, in __run
2020-07-15 16:10:31 CARACal ERROR:     pipeline.run_workers()
2020-07-15 16:10:31 CARACal ERROR:   File "/home/oms/projects/caracal/caracal/workers/worker_administrator.py", line 390, in run_workers
2020-07-15 16:10:31 CARACal ERROR:     worker.worker(self, recipe, config)
2020-07-15 16:10:31 CARACal ERROR:   File "/home/oms/projects/caracal/caracal/workers/crosscal_worker.py", line 474, in worker
2020-07-15 16:10:31 CARACal ERROR:     fluxscale_field = pipeline.fcal[i][0]
2020-07-15 16:10:31 CARACal ERROR: IndexError: list index out of range
2020-07-15 16:10:31 CARACal INFO: exiting with error code 1
```

We can probably throw a more helpful error earlier in the game?

**Comment by o-smirnov** [comment]
Good point @KshitijT -- it did not, but how could it not? I'll have a look in the logs...

**Comment by o-smirnov** [comment]
Ah but of course, it ran with ``field=""``, so it was just a very fancy ``cp -r`` command!

**Comment by KshitijT** [comment]
Note here that _both_ BPCAL and FCAL need to be set manually in such a case. I suggest a setting where if 1)The scan intents are not set 2) Either FCAL or BPCAL is set, then one defaults to the other.
