### ISSUE TITLE
SoFiA Error: Floating point inf values are not allowed in FITS headers.

### ISSUE THREAD

**Issue by ianjarog** [caracal-pipeline/caracal#1246]
@paoloserra  I am getting the following SoFiA errors Floating point inf values are not allowed in FITS headers.

 # --- SoFiA 1.3.2: Writing moment maps ----------------------------------------
#     Elapsed time: 00:03:34.63 h
# 
# Writing moment-0
# Writing moment-1
# Traceback (most recent call last):
#   File "/sofia/sofia_pipeline.py", line 695, in <module>
#     writemoment2.writeMoments(np_Cube, mask, outroot, debug, dict_Header, Parameters["writeCat"]["compress"], write_mom[0], write_mom[1], Parameters["writeCat"]["overwrite"])
#   File "writemoment2.pyx", line 213, in writemoment2.writeMoments
#   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/header.py", line 194, in __setitem__
#     self._update((key, value, comment))
#   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/header.py", line 1632, in _update
#     self.append(card)
#   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/header.py", line 1164, in append
#     card = Card(*card)
#   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/card.py", line 192, in __init__
#     self.value = value
#   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/card.py", line 315, in value
#     "in FITS headers.".format(value))
# ValueError: Floating point inf values are not allowed in FITS headers.
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 61, in <module>
#     subprocess.check_call(shlex.split(_runc))
#   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['sofia_pipeline.py', 'sofia_parameters.par']' returned non-zero exit status 1

**Comment by paoloserra** [comment]
You're probably getting a infinite datamin or datamax in one of the moment images. If there is a problem it needs to be fixed in SoFiA, and then the fix must be rolled into Stimela and CARACal. Any ideas why this might be happening to your cube?

**Comment by paoloserra** [comment]
Just to be clearer: do you have Inf values in your input cube?

**Comment by ianjarog** [comment]
> Just to be clearer: do you have Inf values in your input cube?

@paoloserra numpy.isinf(img).any() turns out to be False. But I think there is something wrong in my input cubes since I cannot even open it on kvis or tigger.

**Comment by paoloserra** [comment]
That's very weird... well, I've opened an issue on the SoFiA repository with the goal of filtering out all Inf's before any processing is done. However, I'm no longer sure this is your problem. Please keep me posted.

Was the cube made with CARACal?

**Comment by ianjarog** [comment]
> That's very weird... well, I've opened an issue on the SoFiA repository with the goal of filtering out all Inf's before any processing is done. However, I'm no longer sure this is your problem. Please keep me posted.
> 
> Was the cube made with CARACal?

Yes the cube was made with CARACal. It's the SoFiA part of CARACal The other cubes went through though (I chunked the ms file in different frequency band and imaged them separately...) I will keep you posted if I figure this out.
