### ISSUE TITLE
Ragavi plotting on ILIFU

### ISSUE THREAD

**Issue by KshitijT** [caracal-pipeline/caracal#1251]
Getting the following error on ILIFU with ragavi-plotting:

```
# [##################################      ] | 87% Completed |  3.4s
# [###################################     ] | 89% Completed |  3.5s
# [#####################################   ] | 94% Completed |  3.6s
# [########################################] | 100% Completed |  3.7s
# 04.10.2020@18:06:49 - ragavi.visibilities  - INFO       - Aggregation done
# 04.10.2020@18:06:49 - ragavi.utils         - INFO       - image_callback executed in: 3.721 sec.
# 04.10.2020@18:06:49 - ragavi.visibilities  - INFO       - Creating Bokeh Figure
# 04.10.2020@18:06:49 - ragavi.visibilities  - INFO       - Plotting complete.
# 04.10.2020@18:06:49 - ragavi               - ERROR      - Oops ... uncaught exception occurred!
# 04.10.2020@18:06:49 - ragavi               - ERROR      - Traceback (most recent call last):
# 04.10.2020@18:06:49 - ragavi               - ERROR      -    File "/usr/local/bin/ragavi-vis", line 21, in <module>
# 04.10.2020@18:06:49 - ragavi               - ERROR      -     main(options=options)
# 04.10.2020@18:06:49 - ragavi               - ERROR      -    File "/usr/local/lib/python3.6/dist-packages/ragavi/utils.py", line 612, in timer
# 04.10.2020@18:06:49 - ragavi               - ERROR      -     ans = func(*args, **kwargs)
# 04.10.2020@18:06:49 - ragavi               - ERROR      -    File "/usr/local/lib/python3.6/dist-packages/ragavi/visibilities.py", line 1776, in main
# 04.10.2020@18:06:49 - ragavi               - ERROR      -     save(final_plot)
# 04.10.2020@18:06:49 - ragavi               - ERROR      -    File "/usr/local/lib/python3.6/dist-packages/bokeh/io/saving.py", line 87, in save
# 04.10.2020@18:06:49 - ragavi               - ERROR      -     _save_helper(obj, filename, resources, title, template, theme)
# 04.10.2020@18:06:49 - ragavi               - ERROR      -    File "/usr/local/lib/python3.6/dist-packages/bokeh/io/saving.py", line 149, in _save_helper
# 04.10.2020@18:06:49 - ragavi               - ERROR      -     html = file_html(obj, resources, title=title, template=template, theme=theme)
# 04.10.2020@18:06:49 - ragavi               - ERROR      -    File "/usr/local/lib/python3.6/dist-packages/bokeh/embed/standalone.py", line 304, in file_html
# 04.10.2020@18:06:49 - ragavi               - ERROR      -     (docs_json, render_items) = standalone_docs_json_and_render_items(models_seq, suppress_callback_warning=suppress_callback_warning)
# 04.10.2020@18:06:49 - ragavi               - ERROR      -    File "/usr/local/lib/python3.6/dist-packages/bokeh/embed/util.py", line 294, in standalone_docs_json_and_render_items
# 04.10.2020@18:06:49 - ragavi               - ERROR      -     docs_json[docid] = doc.to_json()
# 04.10.2020@18:06:49 - ragavi               - ERROR      -    File "/usr/local/lib/python3.6/dist-packages/bokeh/document/document.py", line 882, in to_json
# 04.10.2020@18:06:49 - ragavi               - ERROR      -     doc_json = self.to_json_string()
# 04.10.2020@18:06:49 - ragavi               - ERROR      -    File "/usr/local/lib/python3.6/dist-packages/bokeh/document/document.py", line 911, in to_json_string
# 04.10.2020@18:06:49 - ragavi               - ERROR      -     return serialize_json(json, indent=indent)
# 04.10.2020@18:06:49 - ragavi               - ERROR      -    File "/usr/local/lib/python3.6/dist-packages/bokeh/core/json_encoder.py", line 166, in serialize_json
# 04.10.2020@18:06:49 - ragavi               - ERROR      -     return json.dumps(obj, cls=BokehJSONEncoder, allow_nan=False, indent=indent, separators=separators, sort_keys=True, **kwargs)
# 04.10.2020@18:06:49 - ragavi               - ERROR      -    File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
# 04.10.2020@18:06:49 - ragavi               - ERROR      -     **kw).encode(obj)
# 04.10.2020@18:06:49 - ragavi               - ERROR      -    File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
# 04.10.2020@18:06:49 - ragavi               - ERROR      -     chunks = self.iterencode(o, _one_shot=True)
# 04.10.2020@18:06:49 - ragavi               - ERROR      -    File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
# 04.10.2020@18:06:49 - ragavi               - ERROR      -     return _iterencode(o, 0)
# 04.10.2020@18:06:49 - ragavi               - ERROR      -  ValueError: Out of range float values are not JSON compliant
# 2020-10-04 18:06:50: ragavi-vis exited with code 1
2020-10-04 20:06:50 CARACal.Stimela.plot-real_imag-0-0 ERROR: cd /idia/users/kshitij/m87/.stimela_workdir-16018346483206263 && singularity returns error code 1
2020-10-04 20:06:50 CARACal.Stimela.plot-real_imag-0-0 ERROR: job failed at 2020-10-04 20:06:50.566395 after 0:02:09.720404

```

The corresponding setting in the yml file is: 
```
inspect:
  enable: true
  label_in: 'cal'
  label_plot: '1gc'
  field: 'calibrators'
  real_imag:
    enable: true
    avgtime: '60'
  amp_phase:
    enable: true
    avgtime: '60'
  amp_uvwave:
    enable: true
    avgtime: '60'
  amp_ant:
    enable: true
    avgtime: '60'
  phase_uvwave:
    enable: true
    avgtime: '60'
  amp_scan:
    enable: true
    avgtime: '60'

```
Stimela version being used is 1.6.7 .

Any clues, @Mulan-94 , @o-smirnov ?

**Comment by paoloserra** [comment]
Just a reminder that #1200 (another ragavi error on ILIFU) is also still open.

**Comment by KshitijT** [comment]
Also, this did not happen with older versions of Stimela, so tentatively flagging this as a stimela issue.

**Comment by Mulan-94** [comment]
Hi @KshitijT There's `ragavi:1.7.3` out now and is waiting to go into `stimela` master, which hopefully also fixes #1200 . If possible, may you please test with this image and let me know if it works ?

**Comment by KshitijT** [comment]
Ok, since I see the same error on com08 too (so different machine, docker not singularity) I am going to remove the ILIFU tag and hazard a guess that this has something to do with data size (ran for data < 100 MB, stuck for 10 GB).
@Mulan-94 , could you please point me to the stimela branch where ragavi:1.7.3 is available (if it is) ?

**Comment by Mulan-94** [comment]
Ok the branch is: https://github.com/Mulan-94/Stimela.git@update_ragavi

**Comment by KshitijT** [comment]
Thanks ! Let me check it out.

**Comment by paoloserra** [comment]
I think this is fixed now. Please reopen if necessary.
