### ISSUE TITLE
'worker_administrator' object has no attribute 'set_cal_msnames'

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#1263]
Getting the following error in DDCal worker

2020-10-23 13:22:36 CARACal ERROR: 'worker_administrator' object has no attribute 'set_cal_msnames' [AttributeError]
2020-10-23 13:22:36 CARACal INFO:   More information can be found in the logfile at output/logs-20201023-132234/log-caracal.txt
2020-10-23 13:22:36 CARACal INFO:   You are running version v1.0.3-117-g916c5a11
2020-10-23 13:22:36 CARACal ERROR: Traceback (most recent call last):
2020-10-23 13:22:36 CARACal ERROR:   File "/home/vparekh/caracal/caracal/main.py", line 184, in __run
2020-10-23 13:22:36 CARACal ERROR:     pipeline.run_workers()
2020-10-23 13:22:36 CARACal ERROR:   File "/home/vparekh/caracal/caracal/workers/worker_administrator.py", line 397, in run_workers
2020-10-23 13:22:36 CARACal ERROR:     worker.worker(self, recipe, config)
2020-10-23 13:22:36 CARACal ERROR:   File "/home/vparekh/caracal/caracal/workers/ddcal_worker.py", line 29, in worker
2020-10-23 13:22:36 CARACal ERROR:     pipeline.set_cal_msnames(label)
2020-10-23 13:22:36 CARACal ERROR: AttributeError: 'worker_administrator' object has no attribute 'set_cal_msnames'
2020-10-23 13:22:36 CARACal INFO: exiting with error code 1

[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/5429982/log-caracal.txt)

**Comment by KshitijT** [comment]
It's a bit broken at the moment; on my plate over the weekend.
If you want you can test it out (once I have fixed the issue).

**Comment by KshitijT** [comment]
N.B. @viralp , helping test out code will get you around 27 brownie points per PR; once you have 811 brownie points, you get 10% discount on the next CARACal release version.

Very lucrative scheme, right?

**Comment by viralp** [comment]
@KshitijT Sure I will be happy to test out the code. BTW, what is 10% discount? Access to some secret code to detect big bang signal?

**Comment by o-smirnov** [comment]
No, that only comes in at the Level 5 discount.

Level 1 gets you an opportunity to join a ~death mar~ hike with a real-life Caracal developer!
