### ISSUE TITLE
list index out of range [IndexError]

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#1265]
I am reducing the uGMRT data with Caracal but it seems to be not able to find calibrator fields. Also, I am not quite sure how it will set the flux density standard for uGMRT flux calibrator. There is ```no_verify``` option availbe in the crosscal, does it take PB scale for a given flux calibrator(s)?  
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/5437913/log-caracal.txt)

2020-10-26 09:24:32 CARACal ERROR: list index out of range [IndexError]
2020-10-26 09:24:32 CARACal INFO:   More information can be found in the logfile at output/logs-20201026-090246/log-caracal.txt
2020-10-26 09:24:32 CARACal INFO:   You are running version v1.0.3-117-g916c5a11
2020-10-26 09:24:32 CARACal ERROR: Traceback (most recent call last):
2020-10-26 09:24:32 CARACal ERROR:   File "/home/parekh/caracal/caracal/main.py", line 184, in __run
2020-10-26 09:24:32 CARACal ERROR:     pipeline.run_workers()
2020-10-26 09:24:32 CARACal ERROR:   File "/home/parekh/caracal/caracal/workers/worker_administrator.py", line 397, in run_workers
2020-10-26 09:24:32 CARACal ERROR:     worker.worker(self, recipe, config)
2020-10-26 09:24:32 CARACal ERROR:   File "/home/parekh/caracal/caracal/workers/crosscal_worker.py", line 474, in worker
2020-10-26 09:24:32 CARACal ERROR:     fluxscale_field = pipeline.fcal[i][0]
2020-10-26 09:24:32 CARACal ERROR: IndexError: list index out of range

**Comment by KshitijT** [comment]
Please see if the field intents are defined (for GMRT datasets, they often aren't) - if they aren't, then define the calibrator and target fields manually.

**Comment by o-smirnov** [comment]
I think I pushed a fix to master which makes the error message a bit more clear in this case. Should be out in R1.0.4.

**Comment by KshitijT** [comment]
I think it's a good idea to add a GMRT sample configuration to CARACal. Maybe @o-smirnov and @PeterKamphuis can make one?
