### ISSUE TITLE
PredictNoise breaks with multiple MS'

### ISSUE THREAD

**Issue by dane-kleiner** [caracal-pipeline/caracal#1293]
When running the line worker on multiple (2) MS', the predictNoise.py script breaks:

```
2020-12-01 13:49:21 CARACal INFO:       SINGLE MS median natural noise ignoring flags = 1.616e-04 Jy/beam
2020-12-01 13:49:30 CARACal INFO:     Concatenating all 2 MS files ...
2020-12-01 13:49:30 CARACal INFO:       The concatenated *flag* array has shape (Nr_integrations, Nr_channels, Nr_polarisations) = (12581160, 743, 2)
2020-12-01 13:49:30 CARACal INFO:       The concatenated *interval* array has shape (Nr_integrations) = (12581160,)
2020-12-01 13:49:30 CARACal INFO:       The concatenated *channel* width array has shape (-, Nr_channels) = (1, 743)
2020-12-01 13:49:30 CARACal INFO:       Reshaping arrays ...
2020-12-01 13:50:19 CARACal ERROR: Unable to allocate 139. GiB for an array with shape (12581160, 743, 2) and data type int64 [MemoryError]
2020-12-01 13:50:19 CARACal INFO:   More information can be found in the logfile at output/logs-20201201-134625/log-caracal.txt
2020-12-01 13:50:19 CARACal INFO:   You are running version 1.0.4
2020-12-01 13:50:19 CARACal ERROR: Traceback (most recent call last):
2020-12-01 13:50:19 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/main.py", line 183, in __run
2020-12-01 13:50:19 CARACal ERROR:     pipeline.run_workers()
2020-12-01 13:50:19 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/workers/worker_administrator.py", line 413, in run_workers
2020-12-01 13:50:19 CARACal ERROR:     worker.worker(self, recipe, config)
2020-12-01 13:50:19 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/workers/line_worker.py", line 699, in worker
2020-12-01 13:50:19 CARACal ERROR:     noisy.PredictNoise(['{0:s}/{1:s}'.format(pipeline.msdir,mm) for mm in mslist],str(tsyseff),diam,target,verbose=2)
2020-12-01 13:50:19 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/dispatch_crew/noisy.py", line 181, in PredictNoise
2020-12-01 13:50:19 CARACal ERROR:     unflaggedIntegration=(interval0*(1-flag0.astype(int))).sum(axis=(0,2)) # total integration per channel adding up all UNFLAGGED integrations and polarisations (sec)
2020-12-01 13:50:19 CARACal ERROR: MemoryError: Unable to allocate 139. GiB for an array with shape (12581160, 743, 2) and data type int64
2020-12-01 13:50:19 CARACal INFO: exiting with error code 1
```

For now, if you want to run the line worker (i.e. with multiple MS') and skip this step so it doesn't crash, you can disable it with:
```
predict_noise:
   enable: False
```

**Comment by paoloserra** [comment]
Thanks for catching this. I'm not sure this is an issue related to having multiple MS files. It may. work well with multiple small MS files, and crash with a single, giant file. Some testing needed. Is the 139 GiB of memory that was requested in your case anywhere near the size of the two MS files together?

**Comment by dane-kleiner** [comment]
Nope, the 2 MS are ~ 415 Gb (257 + 158).

**Comment by paoloserra** [comment]
Temporarily disabling this by default in https://github.com/caracal-pipeline/caracal/pull/1294 , ok?

**Comment by paoloserra** [comment]
@o-smirnov @SpheMakh 

https://github.com/caracal-pipeline/caracal/blob/f4c143f8217041dece9065d14266cc52fa64dcf4/caracal/workers/line_worker.py#L699

using

https://github.com/caracal-pipeline/caracal/blob/f4c143f8217041dece9065d14266cc52fa64dcf4/caracal/dispatch_crew/noisy.py#L125

**Comment by dane-kleiner** [comment]
It appears that 

`    unflaggedIntegration=(interval0*(1-flag0.astype(int))).sum(axis=(0,2)) # total integration per channel adding up all UNFLAGGED integrations and polarisations (sec)
    unflaggedIntegration[unflaggedIntegration==0]=np.nan
    rmsUnflagged=np.sqrt(2)*kB*tsyseff/Aant/np.sqrt(channelWidths0*unflaggedIntegration)`

Are the offending lines. In fact, the multiplication between inverval0 and flag0 is for large (e.g. multiple) MS causes it to run out of memory. 

The solution is to read in 1 MS, do the necessary calculations, close the MS and loop through the list of MS with this procedure, rather than read in multiple MS, concatenate them and do the calculations on everything at once.
