### ISSUE TITLE
CARACal crashes on permission error when copying logos

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#1299]
I'm finding that the line which the copies CARACal logos from the local repository to `output/reports/` https://github.com/caracal-pipeline/caracal/blob/3caefccb72eaee9f560c53b8af7733c3038ece68/caracal/notebooks/__init__.py#L23 causes CARACal to crash on a permission error when the `output` folder (as well as `output/reports/` and all its content) was created by a different user, even though I have write access there.

The error is

```
2020-12-15 17:00:23 CARACal INFO: Copying MeerKAT input files into input folder
2020-12-15 17:00:23 CARACal ERROR: [Errno 1] Operation not permitted [PermissionError]
2020-12-15 17:00:23 CARACal INFO:   More information can be found in the logfile at output/logs-20201215-165958/log-caracal.txt
2020-12-15 17:00:23 CARACal INFO:   You are running version 1.0.4
2020-12-15 17:00:23 CARACal ERROR: Traceback (most recent call last):
2020-12-15 17:00:23 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/main.py", line 175, in __run
2020-12-15 17:00:23 CARACal ERROR:     end_worker=options.end_worker, generate_reports=not options.no_reports)
2020-12-15 17:00:23 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/workers/worker_administrator.py", line 138, in __init__
2020-12-15 17:00:23 CARACal ERROR:     self.init_pipeline(prep_input=config["general"]["prep_workspace"])
2020-12-15 17:00:23 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/workers/worker_administrator.py", line 342, in init_pipeline
2020-12-15 17:00:23 CARACal ERROR:     notebooks.setup_default_notebooks(all_nbs, output_dir=self.output, prefix=self.prefix, config=self.config)
2020-12-15 17:00:23 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/site-packages/caracal/notebooks/__init__.py", line 23, in setup_default_notebooks
2020-12-15 17:00:23 CARACal ERROR:     shutil.copy2(png, logodir)
2020-12-15 17:00:23 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/shutil.py", line 264, in copy2
2020-12-15 17:00:23 CARACal ERROR:     copystat(src, dst, follow_symlinks=follow_symlinks)
2020-12-15 17:00:23 CARACal ERROR:   File "/idia/projects/fornax/caracal-venv/lib/python3.6/shutil.py", line 205, in copystat
2020-12-15 17:00:23 CARACal ERROR:     follow_symlinks=follow)
2020-12-15 17:00:23 CARACal ERROR: PermissionError: [Errno 1] Operation not permitted
2020-12-15 17:00:23 CARACal INFO: exiting with error code 1
```

The problem disappears if I replace that line with

```
shutil.copyfile(png, os.path.join(logodir,os.path.basename(png)))
```

I actually don't understand this -- neither the error (I do have write access there) nor the fix. So I'm not sure this is the solution we want, but it does seem to work.

Any clue?

Tagging @o-smirnov and @Jordatious since I mentioned this to them elsewhere.

**Comment by Jordatious** [comment]
Hey @paoloserra, I can reproduce this error now. It seems to be some weird shutil issue with trying to essentially chmod / chown on something you don't own, which is normal. I believe it first copies and then tries to adjust the ownership / permissions / timestamps so that it can retain the same metadata, but fails at the 2nd step, since it's operating on a file you don't own. It's the same in bash. You can't chmod or chown on something you don't own, even with group write permission.

Similar to your solution above, you can first run this, which then allows your original shutil.copy2() to work.

```os.remove(os.path.join(logodir,os.path.basename(png)))```

**Comment by o-smirnov** [comment]
Thanks @Jordatious, that clears up the mystery. @paoloserra's empirically-derived fix now makes perfect sense and we should stick to it (and also check for other uses of ``shutil.copy2`` in the code...)

**Comment by paoloserra** [comment]
thanks @Jordatious !

@o-smirnov here it is, are you suggesting we make a similar change everywhere in the pipeline? https://github.com/caracal-pipeline/caracal/search?q=shutil.copy2

**Comment by o-smirnov** [comment]
Yep, they're all going to fail in the same way in your "not my files but my problems!" workflow (except the last one, which is only called if the file doesn't exist.)

**Comment by paoloserra** [comment]
Alright -- mind if I include the changes in https://github.com/caracal-pipeline/caracal/pull/1294 ? That's the branch we're using for Fornax on Ilifu, which is also where we're having this problem.

**Comment by o-smirnov** [comment]
Sure, you're the only one who needs them ATM.
