### ISSUE TITLE
IndexError: list index out of range in polcal

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1319]
Getting this in the polcal worker:
```
2021-03-26 23:20:24 CARACal.Stimela.set_model_cal-0 INFO: Container [set_model_cal_0-14004342019249616167927380266826] has executed successfully
2021-03-26 23:20:24 CARACal.Stimela.set_model_cal-0 INFO: Runtime was 0:14:33.036801.
2021-03-26 23:20:24 CARACal.Stimela.set_model_cal-0 INFO: job complete at 2021-03-26 23:20:24.187295 after 0:14:33.257003
2021-03-26 23:20:24 CARACal.Stimela.leakage_freq INFO: job started at 2021-03-26 23:20:24.187412
2021-03-26 23:20:24 CARACal.Stimela.polcal INFO: STEP 3 :: leakage_freq
2021-03-26 23:20:24 CARACal.Stimela INFO: Validating parameters for cab casa_polcal (stimela/casa:1.6.3)
2021-03-26 23:20:24 CARACal.Stimela INFO: Location of 'caltable' was specified as 'output'. Will overide default.
2021-03-26 23:20:24 CARACal ERROR: list index out of range [IndexError]
2021-03-26 23:20:24 CARACal INFO:   More information can be found in the logfile at output-od2-polcal/logs-20210326-120353/log-caracal.txt
2021-03-26 23:20:24 CARACal INFO:   You are running version v1.0.4-130-gaad825c4
2021-03-26 23:20:27 CARACal ERROR: Traceback (most recent call last):
2021-03-26 23:20:27 CARACal ERROR:   File "/home/oms/projects/caracal/caracal/main.py", line 183, in __run
2021-03-26 23:20:27 CARACal ERROR:     pipeline.run_workers()
2021-03-26 23:20:27 CARACal ERROR:   File "/home/oms/projects/caracal/caracal/workers/worker_administrator.py", line 441, in run_workers
2021-03-26 23:20:27 CARACal ERROR:     worker.worker(self, recipe, config)
2021-03-26 23:20:27 CARACal ERROR:   File "/home/oms/projects/caracal/caracal/workers/polcal_worker.py", line 1329, in worker
2021-03-26 23:20:27 CARACal ERROR:     prefix, refant, leak_caltablelist, leak_gainfieldlist, leak_interplist, leak_calwtlist, leak_applylist)
2021-03-26 23:20:27 CARACal ERROR:   File "/home/oms/projects/caracal/caracal/workers/polcal_worker.py", line 1073, in calib_only_leakage
2021-03-26 23:20:27 CARACal ERROR:     recipe.run()
2021-03-26 23:20:27 CARACal ERROR:   File "/home/oms/projects/Stimela/stimela/recipe.py", line 703, in run
2021-03-26 23:20:27 CARACal ERROR:     job.run_job()
2021-03-26 23:20:27 CARACal ERROR:   File "/home/oms/projects/Stimela/stimela/recipe.py", line 414, in run_job
2021-03-26 23:20:27 CARACal ERROR:     self.job.parameter_file_name, tag=self.tag)
2021-03-26 23:20:27 CARACal ERROR:   File "/home/oms/projects/Stimela/stimela/cargo/cab/__init__.py", line 386, in update
2021-03-26 23:20:27 CARACal ERROR:     param.validate(value)
2021-03-26 23:20:27 CARACal ERROR:   File "/home/oms/projects/Stimela/stimela/cargo/cab/__init__.py", line 94, in validate
2021-03-26 23:20:27 CARACal ERROR:     elif isinstance(value, list) and isinstance(value[0], tuple([t]+[int] if t is float else [t])):
2021-03-26 23:20:27 CARACal ERROR: IndexError: list index out of range
2021-03-26 23:20:27 CARACal INFO: exiting with error code 1
```
There's a Stimela problem here (@SpheMakh), seems that value is [] in this case, and the type validation falls over instead of complaining about the parameter value properly. Not sure if the ``[]`` is legit or not, looking into it...

**Comment by o-smirnov** [comment]
OK @francescaLoi, this was a Stimela bug (https://github.com/ratt-ru/Stimela/issues/706) triggered when polcal is called with ``gainfield=[]``. I truly don't understand why this hasn't happened before though!

**Comment by paoloserra** [comment]
@o-smirnov I've seen that the associated Stimela issue is closed. We can close this one then, or you're waiting for the  Stimela fix to go into a Stimela release?

**Comment by o-smirnov** [comment]
@SpheMakh comment please.

**Comment by SpheMakh** [comment]
@SpheMakh comment dude!
