### ISSUE TITLE
WSCLEAN error "Can not form requested polarization (Stokes I) from available polarizations"  fails to image stokes I because RR and YY correlations are in different spectral windows --VLA data.

### ISSUE THREAD

**Issue by bnamumba** [caracal-pipeline/caracal#1326]
Reordering /stimela_mount/msdir/out-NGC1156-corr.ms into 16 x 1 parts.
Reordering: 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
+ + + + + + + + + + + + + + + + + + +
+ An exception occured:
+ >>> Can not form requested polarization (Stokes I) from available polarizations
+ + + + + + + + + + + + + + + + + + +
Traceback (most recent call last):
  File "/stimela_mount/code/run.py", line 68, in <module>
    subprocess.check_call(shlex.split(_runc))
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wsclean', '-name', '/stimela_mount/output/continuum/image_1/NGC1156_NGC1156_1', '-j', '54', '-mem', '100', '-absmem', '100.0', '-weight', 'briggs', '-1.0', '-no-mfs-weighting', '-size', '5200', '5200', '-scale', '1.3asec', '-channels-out', '16', '-nwlayers-factor', '3', '-pol', 'I', '-data-column', 'DATA', '-niter', '30000', '-auto-threshold', '0.5', '-auto-mask', '20.0', '-gain', '0.1', '-mgain', '0.9', '-join-channels', '-fit-spectral-pol', '5', '-padding', '1.3', '-save-source-list', '-parallel-deconvolution', '708', '/stimela_mount/msdir/out-NGC1156-corr.ms']' returned non-zero exit status 255.
cd /home/namumba/data1/.stimela_workdir-16194536242224927 && singularity returns error code 1
job failed at 2021-04-26 18:13:59.372311 after 0:00:01.227488
Traceback (most recent call last):
  File "/home/namumba/data1/venv/lib/python3.6/site-packages/stimela/recipe.py", line 709, in run
    job.run_job()
  File "/home/namumba/data1/venv/lib/python3.6/site-packages/stimela/recipe.py", line 421, in run_job
    self.job.run(output_wrangler=self.apply_output_wranglers)
  File "/home/namumba/data1/venv/lib/python3.6/site-packages/stimela/singularity.py", line 128, in run
    env=self._env, logfile=self.logfile)
  File "/home/namumba/data1/venv/lib/python3.6/site-packages/stimela/utils/xrun_poll.py", line 227, in xrun
    raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
stimela.utils.StimelaCabRuntimeError: cd /home/namumba/data1/.stimela_workdir-16194536242224927 && singularity returns error code 1

LISTOBS
2021-04-30 21:46:47	INFO	listobs::ms::summary	Spectral Windows:  (2 unique spectral windows and 2 unique polarization setups)
2021-04-30 21:46:47	INFO	listobs::ms::summary+	  SpwID  Name                                   #Chans   Frame   Ch0(MHz)  ChanWid(kHz)  TotBW(kHz) CtrFreq(MHz)  Corrs
2021-04-30 21:46:47	INFO	listobs::ms::summary+	  0      127*6.1 kHz channels @ 1.42 GHz (BARY)    127   BARY    1418.256         6.104       775.2   1418.6408   RR
2021-04-30 21:46:47	INFO	listobs::ms::summary+	  1      127*6.1 kHz channels @ 1.42 GHz (BARY)    127   BARY    1418.256         6.104       775.2   1418.6408   LL

**Comment by KshitijT** [comment]
@bnamumba , did you try to manually reset the spectral windows IDs to see if that sorts out the issue? If I remember, the actual spectral windows don't have different frequencies, just a different ID.

**Comment by viralp** [comment]
I had a similar issue for dual-frequency GMRT data where each spw has recorded RR and LL only. As @KshitijT mentioned, we need to reset the spw ID manually. The below procedure you can follow -

 Open the casa browseable - then open the ms file - double click table keywords - Polarization - then change the CORR_TYPE from 5 to 1. This will change the corr_type to I. This works with WSClean also to get the clean component file.

**Comment by bnamumba** [comment]
Kshitij, I was trying to use mstranform, but it did not work. Thanks, Viralp. I managed to use browsetable following the instructions you provided. 

wsclean works but another problem in self-calibration, cubical does not recognize the correlation "I" and produces an error. 
"MS with 1 correlation not (yet) supported"

#  Traceback (most recent call last):
#   File "/usr/local/lib/python3.6/dist-packages/cubical/main.py", line 388, in main
#     do_normalize_data=GD["data"]["normalize"]
#   File "/usr/local/lib/python3.6/dist-packages/cubical/data_handler/ms_data_handler.py", line 267, in __init__
#     raise RuntimeError("MS with {} correlations not (yet) supported".format(self.nmscorrs))
# RuntimeError: MS with 1 correlations not (yet) supported
#
# 2021-05-03 16:24:39: gocubical exited with code 1
2021-05-03 16:24:39 CARACal.Stimela.calibrate-cubical-field0-iter1 ERROR: cd /home/namumba/data1/.stimela_workdir-16200505540653112 && singularity returns error code 1
2021-05-03 16:24:39 CARACal.Stimela.calibrate-cubical-field0-iter1 ERROR: job failed at 2021-05-03 16:24:39.732654 after 0:00:04.123868
2021-05-03 16:24:39 CARACal.Stimela.calibrate-cubical-field0-iter1 ERROR: Traceback (most recent call last):
2021-05-03 16:24:39 CARACal.Stimela.calibrate-cubical-field0-iter1 ERROR:   File "/home/namumba/data1/venv/lib/python3.6/site-packages/stimela/recipe.py", line 709, in run
2021-05-03 16:24:39 CARACal.Stimela.calibrate-cubical-field0-iter1 ERROR:     job.run_job()
2021-05-03 16:24:39 CARACal.Stimela.calibrate-cubical-field0-iter1 ERROR:   File "/home/namumba/data1/venv/lib/python3.6/site-packages/stimela/recipe.py", line 421, in run_job
2021-05-03 16:24:39 CARACal.Stimela.calibrate-cubical-field0-iter1 ERROR:     self.job.run(output_wrangler=self.apply_output_wranglers)
2021-05-03 16:24:39 CARACal.Stimela.calibrate-cubical-field0-iter1 ERROR:   File "/home/namumba/data1/venv/lib/python3.6/site-packages/stimela/singularity.py", line 128, in run
2021-05-03 16:24:39 CARACal.Stimela.calibrate-cubical-field0-iter1 ERROR:     env=self._env, logfile=self.logfile)
2021-05-03 16:24:39 CARACal.Stimela.calibrate-cubical-field0-iter1 ERROR:   File "/home/namumba/data1/venv/lib/python3.6/site-packages/stimela/utils/xrun_poll.py", line 227, in xrun
2021-05-03 16:24:39 CARACal.Stimela.calibrate-cubical-field0-iter1 ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2021-05-03 16:24:39 CARACal.Stimela.calibrate-cubical-field0-iter1 ERROR: stimela.utils.StimelaCabRuntimeError: cd /home/namumba/data1/.stimela_workdir-16200505540653112 && singularity returns error code 1
2021-05-03 16:24:39 CARACal.Stimela.selfcal INFO: Completed jobs : ['save-NGC1156_selfcal_before-ms0', 'save-NGC1156_selfcal_before-ms1', 'image-field0-iter1']
2021-05-03 16:24:39 CARACal.Stimela.selfcal INFO: Remaining jobs : ['image-field0-iter2', 'calibrate-cubical-field0-iter2', 'image-field0-iter3', 'calibrate-cubical-field0-iter3', 'image-field0-iter4', 'calibrate-cubical-field0-iter4', 'image-field0-iter5', 'apply_cubical_gains-4-0']
2021-05-03 16:24:39 CARACal.Stimela.selfcal INFO: Logging remaining task: image-field0-iter2:: Make wsclean image (selfcal iter 2)
2021-05-03 16:24:39 CARACal.Stimela.selfcal INFO: Logging remaining task: calibrate-cubical-field0-iter2:: Calibrate step 2 ms=Duse-NGC1156-corr.ms
2021-05-03 16:24:39 CARACal.Stimela.selfcal INFO: Logging remaining task: image-field0-iter3:: Make wsclean image (selfcal iter 3)
2021-05-03 16:24:39 CARACal.Stimela.selfcal INFO: Logging remaining task: calibrate-cubical-field0-iter3:: Calibrate step 3 ms=Duse-NGC1156-corr.ms
2021-05-03 16:24:39 CARACal.Stimela.selfcal INFO: Logging remaining task: image-field0-iter4:: Make wsclean image (selfcal iter 4)
2021-05-03 16:24:39 CARACal.Stimela.selfcal INFO: Logging remaining task: calibrate-cubical-field0-iter4:: Calibrate step 4 ms=Duse-NGC1156-corr.ms
2021-05-03 16:24:39 CARACal.Stimela.selfcal INFO: Logging remaining task: image-field0-iter5:: Make wsclean image (selfcal iter 5)
2021-05-03 16:24:39 CARACal.Stimela.selfcal INFO: Logging remaining task: apply_cubical_gains-4-0:: Apply cubical gains ms=Duse-NGC1156-corr.ms
2021-05-03 16:24:39 CARACal.Stimela.selfcal INFO: Saving pipeline information in .last_selfcal.json
2021-05-03 16:24:39 CARACal ERROR: Job 'calibrate-cubical-field0-iter1:: Calibrate step 1 ms=Duse-NGC1156-corr.ms' failed: cd /home/namumba/data1/.stimela_workdir-16200505540653112 && singularity returns error code 1 [PipelineException]
2021-05-03 16:24:39 CARACal INFO:   More information can be found in the logfile at output/logs-20210503-160233/log-caracal.txt
2021-05-03 16:24:39 CARACal INFO:   You are running version 1.0.4
2021-05-03 16:24:39 CARACal ERROR: Traceback (most recent call last):
2021-05-03 16:24:39 CARACal ERROR:   File "/home/namumba/data1/venv/lib/python3.6/site-packages/caracal/main.py", line 183, in __run
2021-05-03 16:24:39 CARACal ERROR:     pipeline.run_workers()
2021-05-03 16:24:39 CARACal ERROR:   File "/home/namumba/data1/venv/lib/python3.6/site-packages/caracal/workers/worker_administrator.py", line 413, in run_workers
2021-05-03 16:24:39 CARACal ERROR:     worker.worker(self, recipe, config)
2021-05-03 16:24:39 CARACal ERROR:   File "/home/namumba/data1/venv/lib/python3.6/site-packages/caracal/workers/selfcal_worker.py", line 2195, in worker
2021-05-03 16:24:39 CARACal ERROR:     self_cal_iter_counter-1, selfcal_products, mslist_out, enable_inter=True)
2021-05-03 16:24:39 CARACal ERROR:   File "/home/namumba/data1/venv/lib/python3.6/site-packages/caracal/workers/selfcal_worker.py", line 1766, in restore
2021-05-03 16:24:39 CARACal ERROR:     recipe.run()
2021-05-03 16:24:39 CARACal ERROR:   File "/home/namumba/data1/venv/lib/python3.6/site-packages/stimela/recipe.py", line 760, in run
2021-05-03 16:24:39 CARACal ERROR:     raise PipelineException(exc, self.completed, job, self.remaining) from None
2021-05-03 16:24:39 CARACal ERROR: stimela.exceptions.PipelineException: Job 'calibrate-cubical-field0-iter1:: Calibrate step 1 ms=Duse-NGC1156-corr.ms' failed: cd /home/namumba/data1/.stimela_workdir-16200505540653112 && singularity returns error code 1
2021-05-03 16:24:39 CARACal INFO: exiting with error code 1

**Comment by KshitijT** [comment]
@bnamumba , could you please share the cubical log ? @o-smirnov , this error looks familiar, right (single pol data processing with cubical) ?

**Comment by bnamumba** [comment]
[log-selfcal-calibrate-cubical-field0-iter1-20210504-100549.txt](https://github.com/caracal-pipeline/caracal/files/6419941/log-selfcal-calibrate-cubical-field0-iter1-20210504-100549.txt)

**Comment by bnamumba** [comment]
@KshitijT I have shared the cubical log.

**Comment by viralp** [comment]
@KshitijT no I have not tried this.
