### ISSUE TITLE
TypeError encountered by obsconf

### ISSUE THREAD

**Issue by AstroRipples** [caracal-pipeline/caracal#1331]
Hi y'all,

New to using `caracal`, but with help from @francescaLoi I've got myself started on MeerKAT data processing. I'm running the stable release version, which I've installed following the virtualenv instructions. 

`caracal` hits an error shortly after launching, where it's trying to parse the `obsconf` section of inputs. Can't see any reason why, but the traceback is:

```
2021-05-13 17:08:19 CARACal.Stimela.obsconf INFO: ---------------------------------
2021-05-13 17:08:19 CARACal.Stimela.obsconf INFO: Stimela version 1.6.9
2021-05-13 17:08:19 CARACal.Stimela.obsconf INFO: Running: obsconf
2021-05-13 17:08:19 CARACal.Stimela.obsconf INFO: ---------------------------------
2021-05-13 17:08:19 CARACal.Stimela.obsconf INFO: Config directory cannot be found. Will create /local/work/riseley/MeerKAT/ZwCl1454/.stimela_workdir-16209184997039692/stimela_parameter_files
2021-05-13 17:08:19 CARACal INFO: obsconf: initializing
2021-05-13 17:08:19 CARACal ERROR: '<' not supported between instances of 'NoneType' and 'str' [TypeError]
2021-05-13 17:08:19 CARACal INFO:   More information can be found in the logfile at OutputData/logs-20210513-170818/log-caracal.txt
2021-05-13 17:08:19 CARACal INFO:   You are running version 1.0.4
2021-05-13 17:08:19 CARACal ERROR: Traceback (most recent call last):
2021-05-13 17:08:19 CARACal ERROR:   File "/homes/riseley/caracal/lib/python3.7/site-packages/caracal/main.py", line 183, in __run
2021-05-13 17:08:19 CARACal ERROR:     pipeline.run_workers()
2021-05-13 17:08:19 CARACal ERROR:   File "/homes/riseley/caracal/lib/python3.7/site-packages/caracal/workers/worker_administrator.py", line 413, in run_workers
2021-05-13 17:08:19 CARACal ERROR:     worker.worker(self, recipe, config)
2021-05-13 17:08:19 CARACal ERROR:   File "/homes/riseley/caracal/lib/python3.7/site-packages/caracal/workers/obsconf_worker.py", line 45, in worker
2021-05-13 17:08:19 CARACal ERROR:     label='{0:s}:: Get observation information ms={1:s}'.format(step, msname))
2021-05-13 17:08:19 CARACal ERROR:   File "/homes/riseley/caracal/lib/python3.7/site-packages/stimela/recipe.py", line 611, in add
2021-05-13 17:08:19 CARACal ERROR:     repository=self.repository)
2021-05-13 17:08:19 CARACal ERROR:   File "/homes/riseley/caracal/lib/python3.7/site-packages/stimela/recipe.py", line 216, in setup_job
2021-05-13 17:08:19 CARACal ERROR:     time_out=self.time_out)
2021-05-13 17:08:19 CARACal ERROR:   File "/homes/riseley/caracal/lib/python3.7/site-packages/stimela/singularity.py", line 78, in __init__
2021-05-13 17:08:19 CARACal ERROR:     self.name = hashname if version < "3.0.0" else name
2021-05-13 17:08:19 CARACal ERROR: TypeError: '<' not supported between instances of 'NoneType' and 'str'
2021-05-13 17:08:19 CARACal INFO: exiting with error code 1
```

So it looks like `caracal` is trying to get the version name, is failing, and it's trying to compare that number with a string (which seems like it should error regardless of whether it finds the version or not). Presumably this is a bug?

**Comment by o-smirnov** [comment]
Hmmm, looking at the code, it may be as simple as `singularity` not being installed (this is how version ends up as None), but an error to that effect is not reported properly.

So is in installed? Otherwise you can use ``-ct docker``, if you have that.

**Comment by AstroRipples** [comment]
Hey Oleg! Yep, `singularity` is installed. I've been calling `caracal` from within the singularity where I built the virtualenv, via:

```
(caracal) Singularity> caracal -ct singularity -c caracal_zwcl1454_v0.yml
2021-05-14 11:15:02 CARACal INFO: Invoked as /homes/riseley/caracal/bin/caracal -ct singularity -c caracal_zwcl1454_v0.yml
2021-05-14 11:15:04 CARACal INFO: Loading pipeline configuration from caracal_zwcl1454_v0.yml
...
```
and thereafter I get the caracal logo... etc. Would it help if I attached the full log file?

**Comment by o-smirnov** [comment]
Wait, you installed caracal itself inside a singularity container? This is turtles all the way down... not sure it can work like this!

Caracal is meant to be run outside a container, but it will instantiate containers for each processing step.

**Comment by AstroRipples** [comment]
Hmmm ok, I didn't realise that... Had to boot into a singularity to get python3 so I could then launch the actual virtual environment (our cluster is _all kinds of fun_). 

Welp, anyways, now I've nuked my first `caracal` install, re-installed it (and I'll note that `stimela clean -ac`, the command suggested in the "Installation & Run" guide doesn't work, `-ac` doesn't seem to be a recognised option). After a bunch of false starts, I've got `caracal` installed outside of a singularity container 🎉 

However, I **still** get the same error:
```
-bash-4.2$ InitCARACAL
(caracal) -bash-4.2$ caracal -ct singularity -c caracal_zwcl1454_v0.yml
2021-05-14 16:52:41 CARACal INFO: Invoked as /homes/riseley/caracal/bin/caracal -ct singularity -c caracal_zwcl1454_v0.yml
2021-05-14 16:52:46 CARACal INFO: Loading pipeline configuration from caracal_zwcl1454_v0.yml
...
2021-05-14 16:52:49 CARACal INFO: Configuring worker prep
2021-05-14 16:52:49 CARACal INFO: Configuring worker flag
2021-05-14 16:52:49 CARACal INFO: getdata: initializing
2021-05-14 16:52:49 CARACal INFO: getdata: running
2021-05-14 16:52:49 CARACal INFO: getdata: finished
2021-05-14 16:52:49 CARACal INFO: obsconf: initializing
2021-05-14 16:52:49 CARACal ERROR: '<' not supported between instances of 'NoneType' and 'str' [TypeError]
2021-05-14 16:52:49 CARACal INFO:   More information can be found in the logfile at OutputData/logs-20210514-165246/log-caracal.txt
2021-05-14 16:52:49 CARACal INFO: exiting with error code 1
```

So it looks like in vs. out of the singularity is not the issue at hand! 

... 

Le sigh... Turns out to be a terribly "our-cluster-specific" issue, in that singularity is not loaded as a module by default... 🤯  

Closing for now.
