### ISSUE TITLE
caracal run error code 1 when running tranform worker

### ISSUE THREAD

**Issue by Sinah-astro** [caracal-pipeline/caracal#1355]
Running the transform worker, and getting the following error:
```
# Running CASA task 'mstransform'
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 8, in <module>
#     task.run()
#   File "/usr/local/lib/python3.6/dist-packages/Crasa/Crasa.py", line 122, in run
#     raise CasaException("CASA raised a SEVERE exception while running task {0:s}".format(self.task))
# Crasa.Crasa.CasaException: CASA raised a SEVERE exception while running task mstransform
2021-07-07 14:54:47 CARACal.Stimela.split_field-ms0-0 ERROR: cd /home/manaka/masters/.stimela_workdir-16256624819366162 && singularity returns error code 1
2021-07-07 14:54:47 CARACal.Stimela.split_field-ms0-0 ERROR: job failed at 2021-07-07 14:54:47.172478 after 0:00:05.162377
2021-07-07 14:54:47 CARACal.Stimela.split_field-ms0-0 ERROR: Traceback (most recent call last):
2021-07-07 14:54:47 CARACal.Stimela.split_field-ms0-0 ERROR:   File "/home/manaka/software/caracaldir/Stimela/stimela/recipe.py", line 710, in run
2021-07-07 14:54:47 CARACal.Stimela.split_field-ms0-0 ERROR:     job.run_job()
2021-07-07 14:54:47 CARACal.Stimela.split_field-ms0-0 ERROR:   File "/home/manaka/software/caracaldir/Stimela/stimela/recipe.py", line 422, in run_job
2021-07-07 14:54:47 CARACal.Stimela.split_field-ms0-0 ERROR:     self.job.run(output_wrangler=self.apply_output_wranglers)
2021-07-07 14:54:47 CARACal.Stimela.split_field-ms0-0 ERROR:   File "/home/manaka/software/caracaldir/Stimela/stimela/singularity.py", line 128, in run
2021-07-07 14:54:47 CARACal.Stimela.split_field-ms0-0 ERROR:     env=self._env, logfile=self.logfile)
2021-07-07 14:54:47 CARACal.Stimela.split_field-ms0-0 ERROR:   File "/home/manaka/software/caracaldir/Stimela/stimela/utils/xrun_poll.py", line 227, in xrun
2021-07-07 14:54:47 CARACal.Stimela.split_field-ms0-0 ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2021-07-07 14:54:47 CARACal.Stimela.split_field-ms0-0 ERROR: stimela.utils.StimelaCabRuntimeError: cd /home/manaka/masters/.stimela_workdir-16256624819366162 && singularity returns error code 1
2021-07-07 14:54:47 CARACal.Stimela.transform INFO: Completed jobs : []
2021-07-07 14:54:47 CARACal.Stimela.transform INFO: Remaining jobs : ['save-psz254_transform_after-ms0', 'listobs-ms0-0', 'summary_json-ms0-0']
2021-07-07 14:54:47 CARACal.Stimela.transform INFO: Logging remaining task: save-psz254_transform_after-ms0:: Save flag version
2021-07-07 14:54:47 CARACal.Stimela.transform INFO: Logging remaining task: listobs-ms0-0:: Get observation information ms=PSZ2G254-cal.ms
2021-07-07 14:54:47 CARACal.Stimela.transform INFO: Logging remaining task: summary_json-ms0-0:: Get observation information as a json file ms=PSZ2G254-cal.ms
2021-07-07 14:54:47 CARACal.Stimela.transform INFO: Saving pipeline information in .last_transform.json
2021-07-07 14:54:47 CARACal ERROR: Job 'split_field-ms0-0:: Split and average data ms=PSZ2G254.ms' failed: cd /home/manaka/masters/.stimela_workdir-16256624819366162 && singularity returns error code 1 [PipelineException]
2021-07-07 14:54:47 CARACal INFO:   More information can be found in the logfile at output/logs-20210707-145440/log-caracal.txt
2021-07-07 14:54:47 CARACal INFO:   You are running version v1.0.4-172-g712c28ca
2021-07-07 14:54:47 CARACal ERROR: Traceback (most recent call last):
2021-07-07 14:54:47 CARACal ERROR:   File "/home/manaka/software/caracaldir/caracal/caracal/main.py", line 183, in __run
2021-07-07 14:54:47 CARACal ERROR:     pipeline.run_workers()
2021-07-07 14:54:47 CARACal ERROR:   File "/home/manaka/software/caracaldir/caracal/caracal/workers/worker_administrator.py", line 443, in run_workers
2021-07-07 14:54:47 CARACal ERROR:     recipe.run()
2021-07-07 14:54:47 CARACal ERROR:   File "/home/manaka/software/caracaldir/Stimela/stimela/recipe.py", line 761, in run
2021-07-07 14:54:47 CARACal ERROR:     raise PipelineException(exc, self.completed, job, self.remaining) from None
2021-07-07 14:54:47 CARACal ERROR: stimela.exceptions.PipelineException: Job 'split_field-ms0-0:: Split and average data ms=PSZ2G254.ms' failed: cd /home/manaka/masters/.stimela_workdir-16256624819366162 && singularity returns error code 1
2021-07-07 14:54:47 CARACal INFO: exiting with error code 1
```

logfile:
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/6777388/log-caracal.txt)

**Comment by o-smirnov** [comment]
"Mamma mia, here we go again // my my how can I resist you?" should be the CASA theme song!

So the error in the log is this:
```
# 2021-07-07 13:14:08   INFO    ParallelDataHelper::::  Analyzing MS for partitioning
# 2021-07-07 13:14:08   INFO    ParallelDataHelper::::  Input vis is a Multi-MS
# 2021-07-07 13:14:08   SEVERE  open::/stimela_mount/input/PSZ2G254.ms/SUBMSS/J1939-6342-8s.ms  Exception Reported: RegularFileIO: e
rror in open or create of file /stimela_mount/input/PSZ2G254.ms/SUBMSS/J1939-6342-8s.ms/table.dat: Read-only file system
# 2021-07-07 13:14:08   SEVERE  ParallelDataHelper::::  RegularFileIO: error in open or create of file /stimela_mount/input/PSZ2G254
.ms/SUBMSS/J1939-6342-8s.ms/table.dat: Read-only file system
# 2021-07-07 13:14:08   INFO    ParallelDataHelper::::  ##### End Task: mstransform          #####
# 2021-07-07 13:14:08   INFO    ParallelDataHelper::::+ ##########################################
```
For some reason, it is trying to write to the **source** MS. It shouldn't, and it has no right to (which is why Caracal mounts it as read-only), but because it's CASA, it wants to. Why, is a largely rhetorical and useless question.

My guess is that this is because we're using a virtconcat MS. We don't have this problem when splitting from normal MSs, in fact we keep them as readonly all the time (precisely as a precaution, so that ~crappy soft~sophisticated packages don't corrupt our precious raw data.)

Sorry @Sinah-astro, back to square 1. You're going to need to run concat() not virtconcat() on the MSs.

**Comment by Sinah-astro** [comment]
> Sorry @Sinah-astro, back to square 1. You're going to need to run concat() not virtconcat() on the MSs.

So far, the concatenated MS is behaving
