### ISSUE TITLE
WTF singularity error

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#1361]
Sinah's got the pipeline falling over in ways I can't understand. The cab runs, but singularity returns error code 1. The only suspicious thing is the
```
# WARNING: Overriding HOME environment variable with SINGULARITYENV_HOME is not permitted
```
message. Here's a fuller log:
```
2021-07-30 18:57:59 CARACal.Stimela.summary_json-ms0 INFO: Starting container [summary_json_ms0-14029230831294416276642795482972]. Timeout set to -1. The 
container ID is printed below.
# running cd /home/oms/sinah-test/.stimela_workdir-16276642795417333 && singularity run --workdir /home/oms/sinah-test/.stimela_workdir-16276642795417333 
--containall  --bind /home/oms/sinah-test/.stimela_workdir-16276642795417333/stimela_parameter_files/summary_json_ms0-14029230831294416276642795482972.jso
n:/stimela_mount/configfile:ro --bind /home/oms/projects/Stimela/stimela/cargo/cab/msutils/src:/stimela_mount/code:ro --bind /home/oms/sinah-test/.stimela
_workdir-16276642795417333/passwd:/etc/passwd:rw --bind /home/oms/sinah-test/.stimela_workdir-16276642795417333/group:/etc/group:rw --bind /home/oms/.venv/caracal/bin/stimela_runscript:/singularity:ro --bind /home/oms/sinah-test/ms-orig:/stimela_mount/msdir:rw --bind /home/oms/sinah-test/input:/stimela_mount/input:ro --bind /home/oms/sinah-test/test:/stimela_mount/output:rw --bind /home/oms/sinah-test/test/tmp:/stimela_mount/output/tmp:rw /home/oms/sinah-test/stimela_msutils_1.4.6.sif /singularity
# WARNING: Overriding HOME environment variable with SINGULARITYENV_HOME is not permitted
# Successful readonly open of default-locked table /stimela_mount/msdir/PSZ2G254.ms: 24 columns, 2738106 rows
# Successful readonly open of default-locked table /stimela_mount/msdir/PSZ2G254.ms::FIELD: 9 columns, 4 rows
# Successful readonly open of default-locked table /stimela_mount/msdir/PSZ2G254.ms::SPECTRAL_WINDOW: 14 columns, 1 rows
# Successful readonly open of default-locked table /stimela_mount/msdir/PSZ2G254.ms::ANTENNA: 8 columns, 62 rows
# Successful readonly open of default-locked table /stimela_mount/msdir/PSZ2G254.ms::STATE: 7 columns, 4 rows
# Successful readonly open of default-locked table /stimela_mount/msdir/PSZ2G254.ms::POLARIZATION: 4 columns, 1 rows
2021-07-30 18:58:02 CARACal.Stimela.summary_json-ms0 ERROR: cd /home/oms/sinah-test/.stimela_workdir-16276642795417333 && singularity returns error code 1
2021-07-30 18:58:02 CARACal.Stimela.summary_json-ms0 ERROR: job failed at 2021-07-30 18:58:02.623219 after 0:00:03.052343
2021-07-30 18:58:02 CARACal.Stimela.summary_json-ms0 ERROR: Traceback (most recent call last):
2021-07-30 18:58:02 CARACal.Stimela.summary_json-ms0 ERROR:   File "/home/oms/projects/Stimela/stimela/recipe.py", line 710, in run
2021-07-30 18:58:02 CARACal.Stimela.summary_json-ms0 ERROR:     job.run_job()
2021-07-30 18:58:02 CARACal.Stimela.summary_json-ms0 ERROR:   File "/home/oms/projects/Stimela/stimela/recipe.py", line 422, in run_job
2021-07-30 18:58:02 CARACal.Stimela.summary_json-ms0 ERROR:     self.job.run(output_wrangler=self.apply_output_wranglers)
2021-07-30 18:58:02 CARACal.Stimela.summary_json-ms0 ERROR:   File "/home/oms/projects/Stimela/stimela/singularity.py", line 128, in run
2021-07-30 18:58:02 CARACal.Stimela.summary_json-ms0 ERROR:     env=self._env, logfile=self.logfile)
2021-07-30 18:58:02 CARACal.Stimela.summary_json-ms0 ERROR:   File "/home/oms/projects/Stimela/stimela/utils/xrun_poll.py", line 227, in xrun
2021-07-30 18:58:02 CARACal.Stimela.summary_json-ms0 ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2021-07-30 18:58:02 CARACal.Stimela.summary_json-ms0 ERROR: stimela.utils.StimelaCabRuntimeError: cd /home/oms/sinah-test/.stimela_workdir-16276642795417333 && singularity returns error code 1
2021-07-30 18:58:02 CARACal.Stimela.obsconf INFO: Completed jobs : []
2021-07-30 18:58:02 CARACal.Stimela.obsconf INFO: Remaining jobs : []
2021-07-30 18:58:02 CARACal.Stimela.obsconf INFO: Saving pipeline information in .last_obsconf.json
2021-07-30 18:58:02 CARACal ERROR: Job 'summary_json-ms0:: Get observation information as a json file ms=PSZ2G254.ms' failed: cd /home/oms/sinah-test/.stimela_workdir-16276642795417333 && singularity returns error code 1 [PipelineException]
2021-07-30 18:58:02 CARACal INFO:   More information can be found in the logfile at output/logs-20210730-185758/log-caracal.txt
2021-07-30 18:58:02 CARACal INFO:   You are running version v1.0.4-172-g712c28ca
2021-07-30 18:58:02 CARACal ERROR: Traceback (most recent call last):
2021-07-30 18:58:02 CARACal ERROR:   File "/home/oms/projects/caracal/caracal/main.py", line 183, in __run
2021-07-30 18:58:02 CARACal ERROR:     pipeline.run_workers()
2021-07-30 18:58:02 CARACal ERROR:   File "/home/oms/projects/caracal/caracal/workers/worker_administrator.py", line 441, in run_workers
```
The same thing runs fine in docker. I have no clue?

**Comment by KshitijT** [comment]
Just out of interest, how was the pipeline run command given?

**Comment by o-smirnov** [comment]
Very boringly:
```
caracal -ct singularity -c test254.yml
```

**Comment by KshitijT** [comment]
Weird, I see the same error too, but that doesn't seem to stop the pipeline or obsconf from running.

**Comment by o-smirnov** [comment]
Well it's a warning not an error, so maybe it's not the problem. Sinah's pipeline falls over on obsconf, but it still generates the json file (since the container run is actually successful despite the error code). Then when you run it again, it goes a step further since the json file is already there. Are you running on a Rhodes machine?

**Comment by KshitijT** [comment]
> Are you running on a Rhodes machine?

On tina.

**Comment by o-smirnov** [comment]
Cool, let me try it there...

**Comment by o-smirnov** [comment]
@Sinah-astro FYI (well not so much "I" as "lack of I", but you get the sentiment).

**Comment by o-smirnov** [comment]
Ahh thanks for that pointer, @KshitijT. Indeed it runs for me on tina too. So now just to figure out what the difference between the boxes is...

**Comment by o-smirnov** [comment]
Gah ok! Updating to the latest Caracal ``master`` fixes the issue for me (was there some singularity fix done recently? I don't remember. But I'll take it!) @Sinah-astro please try that, and reopen the issue if your problem persists.

**Comment by Sinah-astro** [comment]
> Gah ok! Updating to the latest Caracal `master` fixes the issue for me (was there some singularity fix done recently? I don't remember. But I'll take it!) @Sinah-astro please try that, and reopen the issue if your problem persists.

Even after attempting this. The error is still persistent.

**Comment by o-smirnov** [comment]
Yeah @Sinah-astro is right, this was a false dawn. I was confused yesterday. In fact, the error persists.

**Comment by o-smirnov** [comment]
Yeah I don't know what's going on here. Need @SpheMakh to sort this one out. I modified the stimela runscript to read as follows:
```
!/usr/bin/env bash
set -e
set -u
echo "going into xvfb-run"
xvfb-run -a `which python` $STIMELA_MOUNT/code/run.py 2>&1
echo "exit code: $?" 1>&2
echo "FINISHED!" 1>&2
```
...and it prints 
```
021-07-31 12:26:40 CARACal.Stimela.summary_json-ms0 INFO: job started at 2021-07-31 12:26:40.986675
# WARNING: Overriding HOME environment variable with SINGULARITYENV_HOME is not permitted
# going into xvfb-run
# Successful readonly open of default-locked table /stimela_mount/msdir/PSZ2G254.ms: 24 columns, 2738106 rows
# Successful readonly open of default-locked table /stimela_mount/msdir/PSZ2G254.ms::FIELD: 9 columns, 4 rows
# Successful readonly open of default-locked table /stimela_mount/msdir/PSZ2G254.ms::SPECTRAL_WINDOW: 14 columns, 1 rows
# Successful readonly open of default-locked table /stimela_mount/msdir/PSZ2G254.ms::ANTENNA: 8 columns, 62 rows
# Successful readonly open of default-locked table /stimela_mount/msdir/PSZ2G254.ms::STATE: 7 columns, 4 rows
# Successful readonly open of default-locked table /stimela_mount/msdir/PSZ2G254.ms::POLARIZATION: 4 columns, 1 rows
2021-07-31 12:26:44 CARACal.Stimela.summary_json-ms0 ERROR: cd /home/oms/sinah-test/.stimela_workdir-16277272009580839 && singularity returns error code 1
```
...so clearly ``xvfb-run run.py`` bails out somehow? Note how it does not get to the echo statement afterwards.

**Comment by o-smirnov** [comment]
OK I think I see the prolem (although it is a surprising one). There were 30+ singularity runs that had been Ctrl+Z'd on this system. Cleaning them out with kill, and voila, everything works again.

So bottom line is, there is a hidden global limit on the number of containers that can be run. It's not an unreasonable limit, but it's not nigh, it's mysterious, and it does lead to virtually undiagnosable errors, so user beware.
