### ISSUE TITLE
stimela.exceptions.StimelaCabParameterError: Parameter plot is unknown

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#1363]
Hi. I am getting the following error in the `flag` worker with `summary: True`

2021-08-10 17:05:36 CARACal.Stimela.flag INFO: STEP 7 :: flag-summary-ms0:: Flagging summary  ms=A3376A_GCLS-cal.ms
2021-08-10 17:05:36 CARACal.Stimela INFO: Validating parameters for cab flagstats (stimela/msutils:1.6.0)
2021-08-10 17:05:36 CARACal.Stimela.flag-summary-ms0 ERROR: Parameter plot is unknown. Run 'stimela cabs -i flagstats' to get help on this cab
2021-08-10 17:05:36 CARACal.Stimela.flag-summary-ms0 ERROR: job failed at 2021-08-10 17:05:36.622025 after 0:00:00.000952
2021-08-10 17:05:36 CARACal.Stimela.flag-summary-ms0 ERROR: Traceback (most recent call last):
2021-08-10 17:05:36 CARACal.Stimela.flag-summary-ms0 ERROR:   File "/home/vparekh/Stimela/stimela/recipe.py", line 703, in run
2021-08-10 17:05:36 CARACal.Stimela.flag-summary-ms0 ERROR:     job.run_job()
2021-08-10 17:05:36 CARACal.Stimela.flag-summary-ms0 ERROR:   File "/home/vparekh/Stimela/stimela/recipe.py", line 414, in run_job
2021-08-10 17:05:36 CARACal.Stimela.flag-summary-ms0 ERROR:     self.job.parameter_file_name, tag=self.tag)
2021-08-10 17:05:36 CARACal.Stimela.flag-summary-ms0 ERROR:   File "/home/vparekh/Stimela/stimela/cargo/cab/__init__.py", line 390, in update
2021-08-10 17:05:36 CARACal.Stimela.flag-summary-ms0 ERROR:     "Parameter {0} is unknown. Run 'stimela cabs -i {1}' to get help on this cab".format(name, self.task))
2021-08-10 17:05:36 CARACal.Stimela.flag-summary-ms0 ERROR: stimela.exceptions.StimelaCabParameterError: Parameter plot is unknown. Run 'stimela cabs -i flagstats' to get help on this cab
2021-08-10 17:05:36 CARACal.Stimela.flag INFO: Completed jobs : ['save-mypipelinerun_flag_before-ms0', 'flag-autopowerspec-ms0', 'flag-autocorr-ms0', 'flag-spw-ms0', 'flag-mask-ms0', 'flag-rfi-ms0']
2021-08-10 17:05:36 CARACal.Stimela.flag INFO: Remaining jobs : []
2021-08-10 17:05:36 CARACal.Stimela.flag INFO: Saving pipeline information in .last_flag.json
2021-08-10 17:05:36 CARACal ERROR: Job 'flag-summary-ms0:: Flagging summary  ms=A3376A_GCLS-cal.ms' failed: Parameter plot is unknown. Run 'stimela cabs -i flagstats' to get help on this cab [PipelineException]
2021-08-10 17:05:36 CARACal INFO:   More information can be found in the logfile at output/logs-20210810-163504/log-caracal.txt
2021-08-10 17:05:36 CARACal INFO:   You are running version v1.0.4-191-g081ac8b9
2021-08-10 17:05:36 CARACal ERROR: Traceback (most recent call last):
2021-08-10 17:05:36 CARACal ERROR:   File "/home/vparekh/caracal/caracal/main.py", line 183, in __run
2021-08-10 17:05:36 CARACal ERROR:     pipeline.run_workers()
2021-08-10 17:05:36 CARACal ERROR:   File "/home/vparekh/caracal/caracal/workers/worker_administrator.py", line 441, in run_workers
2021-08-10 17:05:36 CARACal ERROR:     worker.worker(self, recipe, config)
2021-08-10 17:05:36 CARACal ERROR:   File "/home/vparekh/caracal/caracal/workers/flag_worker.py", line 523, in worker
2021-08-10 17:05:36 CARACal ERROR:     recipe.run()
2021-08-10 17:05:36 CARACal ERROR:   File "/home/vparekh/Stimela/stimela/recipe.py", line 754, in run
2021-08-10 17:05:36 CARACal ERROR:     raise PipelineException(exc, self.completed, job, self.remaining) from None
2021-08-10 17:05:36 CARACal ERROR: stimela.exceptions.PipelineException: Job 'flag-summary-ms0:: Flagging summary  ms=A3376A_GCLS-cal.ms' failed: Parameter plot is unknown. Run 'stimela cabs -i flagstats' to get help on this cab
2021-08-10 17:05:36 CARACal INFO: exiting with error code 1
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/6964847/log-caracal.txt)

**Comment by Athanaseus** [comment]
Hi @viralp can you please update your stimela version to latest release `1.7.0`?

**Comment by viralp** [comment]
After updating the stimela, getting following error
```
# running cd /data3/vparekh/A3376 && singularity pull  --name stimela_msutils_1.6.9.sif docker://docker-registry.mirror.ac.za/quay.io/stimela/msutils:1.6.9
# FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://docker-registry.mirror.ac.za/quay.io/stimela/msutils:1.6.9: Error reading manifest 1.6.9 in docker-registry.mirror.ac.za/quay.io/stimela/msutils: manifest unknown: manifest unknown
2021-08-11 12:15:43 CARACal ERROR: cd /data3/vparekh/A3376 && singularity returns error code 255 [StimelaCabRuntimeError]
2021-08-11 12:15:43 CARACal INFO:   More information can be found in the logfile at output/logs-20210811-120859/log-caracal.txt
2021-08-11 12:15:43 CARACal INFO:   You are running version v1.0.4-191-g081ac8b9
2021-08-11 12:15:43 CARACal ERROR: Traceback (most recent call last):
2021-08-11 12:15:43 CARACal ERROR:   File "/home/vparekh/caracal/caracal/main.py", line 183, in __run
2021-08-11 12:15:43 CARACal ERROR:     pipeline.run_workers()
2021-08-11 12:15:43 CARACal ERROR:   File "/home/vparekh/caracal/caracal/workers/worker_administrator.py", line 441, in run_workers
2021-08-11 12:15:43 CARACal ERROR:     worker.worker(self, recipe, config)
2021-08-11 12:15:43 CARACal ERROR:   File "/home/vparekh/caracal/caracal/workers/flag_worker.py", line 522, in worker
2021-08-11 12:15:43 CARACal ERROR:     label='{0:s}:: Flagging summary  ms={1:s}'.format(step, msname))
2021-08-11 12:15:43 CARACal ERROR:   File "/home/vparekh/Stimela/stimela/recipe.py", line 612, in add
2021-08-11 12:15:43 CARACal ERROR:     repository=self.repository)
2021-08-11 12:15:43 CARACal ERROR:   File "/home/vparekh/Stimela/stimela/recipe.py", line 296, in setup_job
2021-08-11 12:15:43 CARACal ERROR:     os.path.basename(cont.image), directory=singularity_image_dir)
2021-08-11 12:15:43 CARACal ERROR:   File "/home/vparekh/Stimela/stimela/singularity.py", line 47, in pull
2021-08-11 12:15:43 CARACal ERROR:     name, fp])
2021-08-11 12:15:43 CARACal ERROR:   File "/home/vparekh/Stimela/stimela/utils/xrun_poll.py", line 227, in xrun
2021-08-11 12:15:43 CARACal ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2021-08-11 12:15:43 CARACal ERROR: stimela.utils.StimelaCabRuntimeError: cd /data3/vparekh/A3376 && singularity returns error code 255
2021-08-11 12:15:43 CARACal INFO: exiting with error code 1
```

**Comment by Athanaseus** [comment]
Try removing ~./singularity/cache and re-run.

`rm -r ~./singularity/cache` or/and `rm -r ~/.singularity`.

**Comment by SpheMakh** [comment]
@viralp is this fixed?

**Comment by Athanaseus** [comment]
Please re-open if experiencing the issue.
