### ISSUE TITLE
error in inspect__polcal  worker

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#1399]
Hi 

I am getting the following error in the `inspect__polcal` worker. Why it is looking for the wrong file?
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/7911309/log-caracal.txt)
[A1795_meerkat_pol.txt](https://github.com/caracal-pipeline/caracal/files/7911343/A1795_meerkat_pol.txt)
```
2022-01-18 01:03:38 CARACal INFO: inspect__polcal: initializing
2022-01-18 01:03:38 CARACal ERROR: MS A1795_raw_vis-1pcal.ms does not exist. Please check that is where it should be. [OSError]
2022-01-18 01:03:38 CARACal INFO:   More information can be found in the logfile at output/logs-20220117-164127/log-caracal.txt
2022-01-18 01:03:38 CARACal INFO:   You are running version 1.0.5-24-ga60628ba
2022-01-18 01:03:38 CARACal ERROR: Traceback (most recent call last):
2022-01-18 01:03:38 CARACal ERROR:   File "/home/parekh/caracal/caracal/main.py", line 187, in __run
2022-01-18 01:03:38 CARACal ERROR:     pipeline.run_workers()
2022-01-18 01:03:38 CARACal ERROR:   File "/home/parekh/caracal/caracal/workers/worker_administrator.py", line 441, in run_workers
2022-01-18 01:03:38 CARACal ERROR:     worker.worker(self, recipe, config)
2022-01-18 01:03:38 CARACal ERROR:   File "/home/parekh/caracal/caracal/workers/inspect_worker.py", line 573, in worker
2022-01-18 01:03:38 CARACal ERROR:     raise IOError(f"MS {ms} does not exist. Please check that is where it should be.")
2022-01-18 01:03:38 CARACal ERROR: OSError: MS A1795_raw_vis-1pcal.ms does not exist. Please check that is where it should be.
```

**Comment by francescaLoi** [comment]
Hi @viralp , you are setting the wrong label in the `inspect__polcal` worker.  This should work:

```
inspect__polcal: 
  enable: true
  label_in: cal
```
