### ISSUE TITLE
Too many files open --Line worker

### ISSUE THREAD

**Issue by SpaceMeerkat** [caracal-pipeline/caracal#1414]
Hi,

I encountered the following error when, running a line worker on my own machine. 

Any help on why too many files would open would be greatly appreciated! 

Note: The line worker section of the config file is copied at the bottom of this post in case it's useful.

Many thanks in advance

```
# + An exception occured:
# + >>> FiledesIO: file /stimela_mount/msdir/1645032076_sub-PGC75143-corr_mst.ms/table.f5 could not be opened: Too many open files
# + + + + + + + + + + + + + + + + + + +
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 69, in <module>
#     subprocess.check_call(shlex.split(_runc))
#   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['wsclean', '-name', '/stimela_mount/output/cubes/cube_1/DDT_PGC75143_lw20_05_2dg_1', '-mem', '100', '-no-update-model-required', '-weight', 'briggs', '0.500', '-taper-gaussian', '20.0', '-size', '1200', '1200', '-scale', '6.0asec', '-channels-out', '498', '-pol', 'I', '-channel-range', '0', '498', '-niter', '1000000', '-auto-threshold', '0.5', '-auto-mask', '10.0', '-gain', '0.1', '-mgain', '1.0', '-multiscale-scale-bias', '0.6', '-padding', '1.2', '/stimela_mount/msdir/1645032076_sub-PGC75143-corr_mst.ms']' returned non-zero exit status 255.
2022-03-14 14:22:57 CARACal.Stimela.make_cube-lw20_05_2dg-field0-iter1-with_automasking ERROR: cd /vault2-ike/dawsonj5/DDT/4K/.stimela_workdir-164726054900541 && singularity returns error code 1
2022-03-14 14:22:57 CARACal.Stimela.make_cube-lw20_05_2dg-field0-iter1-with_automasking ERROR: job failed at 2022-03-14 14:22:57.248011 after 0:00:01.578625
2022-03-14 14:22:57 CARACal.Stimela.make_cube-lw20_05_2dg-field0-iter1-with_automasking ERROR: Traceback (most recent call last):
2022-03-14 14:22:57 CARACal.Stimela.make_cube-lw20_05_2dg-field0-iter1-with_automasking ERROR:   File "/vault2-ike/dawsonj5/caracal-venv/lib/python3.6/site-packages/stimela/recipe.py", line 713, in run
2022-03-14 14:22:57 CARACal.Stimela.make_cube-lw20_05_2dg-field0-iter1-with_automasking ERROR:     job.run_job()
2022-03-14 14:22:57 CARACal.Stimela.make_cube-lw20_05_2dg-field0-iter1-with_automasking ERROR:   File "/vault2-ike/dawsonj5/caracal-venv/lib/python3.6/site-packages/stimela/recipe.py", line 425, in run_job
2022-03-14 14:22:57 CARACal.Stimela.make_cube-lw20_05_2dg-field0-iter1-with_automasking ERROR:     self.job.run(output_wrangler=self.apply_output_wranglers)
2022-03-14 14:22:57 CARACal.Stimela.make_cube-lw20_05_2dg-field0-iter1-with_automasking ERROR:   File "/vault2-ike/dawsonj5/caracal-venv/lib/python3.6/site-packages/stimela/singularity.py", line 128, in run
2022-03-14 14:22:57 CARACal.Stimela.make_cube-lw20_05_2dg-field0-iter1-with_automasking ERROR:     env=self._env, logfile=self.logfile)
2022-03-14 14:22:57 CARACal.Stimela.make_cube-lw20_05_2dg-field0-iter1-with_automasking ERROR:   File "/vault2-ike/dawsonj5/caracal-venv/lib/python3.6/site-packages/stimela/utils/xrun_poll.py", line 227, in xrun
2022-03-14 14:22:57 CARACal.Stimela.make_cube-lw20_05_2dg-field0-iter1-with_automasking ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2022-03-14 14:22:57 CARACal.Stimela.make_cube-lw20_05_2dg-field0-iter1-with_automasking ERROR: stimela.utils.StimelaCabRuntimeError: cd /vault2-ike/dawsonj5/DDT/4K/.stimela_workdir-164726054900541 && singularity returns error code 1
2022-03-14 14:22:57 CARACal.Stimela.line INFO: Completed jobs : ['version_DDT_line_before_ms0', 'delete-flag_versions-after-DDT_line_before-ms0_0']
2022-03-14 14:22:57 CARACal.Stimela.line INFO: Remaining jobs : []
2022-03-14 14:22:57 CARACal.Stimela.line INFO: Saving pipeline information in .last_line.json
2022-03-14 14:22:57 CARACal ERROR: Job 'make_cube-lw20_05_2dg-field0-iter1-with_automasking:: Image Line' failed: cd /vault2-ike/dawsonj5/DDT/4K/.stimela_workdir-164726054900541 && singularity returns error code 1 [PipelineException]
2022-03-14 14:22:57 CARACal INFO:   More information can be found in the logfile at /vault2-ike/dawsonj5/DDT/4K/output/logs-20220314-142226/log-caracal.txt
2022-03-14 14:22:57 CARACal INFO:   You are running version 1.0.6
2022-03-14 14:22:57 CARACal ERROR: Traceback (most recent call last):
2022-03-14 14:22:57 CARACal ERROR:   File "/vault2-ike/dawsonj5/caracal-venv/lib/python3.6/site-packages/caracal/main.py", line 187, in __run
2022-03-14 14:22:57 CARACal ERROR:     pipeline.run_workers()
2022-03-14 14:22:57 CARACal ERROR:   File "/vault2-ike/dawsonj5/caracal-venv/lib/python3.6/site-packages/caracal/workers/worker_administrator.py", line 441, in run_workers
2022-03-14 14:22:57 CARACal ERROR:     worker.worker(self, recipe, config)
2022-03-14 14:22:57 CARACal ERROR:   File "/vault2-ike/dawsonj5/caracal-venv/lib/python3.6/site-packages/caracal/workers/line_worker.py", line 1017, in worker
2022-03-14 14:22:57 CARACal ERROR:     recipe.run()
2022-03-14 14:22:57 CARACal ERROR:   File "/vault2-ike/dawsonj5/caracal-venv/lib/python3.6/site-packages/stimela/recipe.py", line 764, in run
2022-03-14 14:22:57 CARACal ERROR:     raise PipelineException(exc, self.completed, job, self.remaining) from None
2022-03-14 14:22:57 CARACal ERROR: stimela.exceptions.PipelineException: Job 'make_cube-lw20_05_2dg-field0-iter1-with_automasking:: Image Line' failed: cd /vault2-ike/dawsonj5/DDT/4K/.stimela_workdir-164726054900541 && singularity returns error code 1
2022-03-14 14:22:57 CARACal INFO: exiting with error code 1
```

---------------------------------------------------------------------------------------

```
line:
  enable: true
  label_in: corr
  restfreq: '1.420405752GHz'
  line_name: lw20_05_2dg
  subtractmodelcol:
    enable: false
  addmodelcol:
    enable: false
  mstransform:
    enable: false
    doppler:
      enable: true
      telescope: meerkat
    uvlin:
      enable: true
      fitorder: 4
  flag_mst_errors:
    enable: false
    strategy: 'postmst.rfis'
  make_cube:
    enable: true
    npix: [1200]
    cell: 6
    robust: 0.5
    taper: 20
    niter: 1000000
    wscl_mgain: 1
    wscl_nrdeconvsubimg: 1
    wscl_sofia_niter: 3
  pb_cube:
    enable: false
    apply_pb: true
  remove_stokes_axis:
    enable: true
  freq_to_vel:
    enable: true
  report: true
```

**Comment by paoloserra** [comment]
Can you check whether this is the same problem as in https://github.com/caracal-pipeline/caracal/issues/998 ? See `ulimit`.

**Comment by SpaceMeerkat** [comment]
Thanks for the link, just checking now to see if that solves the problem. The thread looks very promising..
________________________________

**Comment by paoloserra** [comment]
great!
