### ISSUE TITLE
J0137+3309(3C48) as a standard polarization calibrator?

### ISSUE THREAD

**Issue by Sinenhlanhla** [caracal-pipeline/caracal#1416]
I get the error below when I try to execute the polcal worker
2022-03-23 10:55:47 CARACal ERROR: Unable to determine pol_calib=xcal. Is your obsconf section configured properly?Your setting of pol_calib=xcal selects J0137+3309.
                                    Supported calibrators are 3C138, 3C286, J1130-1449, J1331+3030, J0521+1638.
                                    Alternatively, you can calibrate both leakage and polarization using a (known or unknown) polarized source
                    observed at several parallactic angles. Configure this source as obsconf:xcal, and leakage_calib=pol_calib=xcal. [RuntimeError]
2022-03-23 10:55:47 CARACal INFO:   More information can be found in the logfile at output/logs-20220323-105545/log-caracal.txt

Is it possible to add J0137+3309(3C48) as a standard polarization calibrator?

**Comment by bennahugo** [comment]
This for MeerKAT data? A note that 3C48 is essentially unpolarized below S-band subband 3. It has been removed from katconfig as HV phase calibrator

**Comment by Sinenhlanhla** [comment]
Yes, it is for MeerKAT data.

**Comment by Sinenhlanhla** [comment]
I've tried deriving the calibration tables by fitting the parallactic angle of J0137+3309, but I get the following error

# 2022-03-29 08:12:56	INFO	polfromgain::::+	##########################################
# 2022-03-29 08:12:56	INFO	polfromgain::::+	##### Begin Task: polfromgain        #####
# 2022-03-29 08:12:56	INFO	polfromgain::::	polfromgain(vis="/stimela_mount/msdir/cfp2020_4b-cal.ms",tablein="/stimela_mount/output/merghers_4b-cfp2020_4b-1pcal.Gpol1",caltable="/stimela_mount/output/merghers_4b-cfp2020_4b-1pcal.Gpol1a",paoffset=0.0)
# 2022-03-29 08:12:56	INFO	polfromgain::::	Deriving calibrator linear polarization from gain ratios.
# 2022-03-29 08:12:56	INFO	msmetadata_cmpt.cc::open	Performing internal consistency checks on /stimela_mount/msdir/cfp2020_4b-cal.ms...
# 2022-03-29 08:12:56	INFO	polfromgain::::	New caltable, /stimela_mount/output/merghers_4b-cfp2020_4b-1pcal.Gpol1a, corrected for linear polarization, will be generated.
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=0 (PA offset=-90.0deg) q=0.168457553917 u=0.155300224875 p=0.229120290062 x=21.3364066155 Gx/Gy=1.16162642693
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=1 (PA offset=-90.0deg) q=0.292388642025 u=0.266129865842 p=0.395368465458 x=21.1541090748 Gx/Gy=1.47203025836
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=2 (PA offset=-90.0deg) q=0.128918267804 u=0.116848669674 p=0.173992906114 x=21.0942334288 Gx/Gy=1.10668678609
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=3 (PA offset=-90.0deg) q=0.0636505881544 u=0.0564757627768 p=0.0850935317966 x=20.7909685417 Gx/Gy=1.04418125163
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=4 (PA offset=-90.0deg) q=-0.153797503331 u=-0.162460232206 p=0.223711866201 x=-66.7154915567 Gx/Gy=0.910186943486
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=5 (PA offset=-90.0deg) q=0.258452147284 u=0.232978527976 p=0.347960496226 x=21.0163464231 Gx/Gy=1.34249364613
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=6 (PA offset=-90.0deg) q=0.209685615702 u=0.194703105667 p=0.286142196799 x=21.4390874641 Gx/Gy=1.23504656418
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=7 (PA offset=-90.0deg) q=0.28465650323 u=0.254115064358 p=0.381580647786 x=20.8777681804 Gx/Gy=1.42990659946
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=8 (PA offset=-90.0deg) q=0.14756031041 u=0.138493050477 p=0.202371861282 x=21.5922290955 Gx/Gy=1.13319484404
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=9 (PA offset=-90.0deg) q=-0.0664840758879 u=-0.0686095003902 p=0.0955374057135 x=-67.0493205127 Gx/Gy=0.953632578642
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=10 (PA offset=-90.0deg) q=0.215151449525 u=0.188737823598 p=0.286202921525 x=20.6291441023 Gx/Gy=1.23083625711
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=11 (PA offset=-90.0deg) q=0.199371566919 u=0.18815681082 p=0.274138664098 x=21.6711846874 Gx/Gy=1.21422458129
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=12 (PA offset=-90.0deg) q=-0.0967837263597 u=-0.088745772888 p=0.131312230556 x=-68.740376841 Gx/Gy=0.939875296632
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=13 (PA offset=-90.0deg) q=0.0366073249246 u=0.0422168311343 p=0.0558780553452 x=24.5352904408 Gx/Gy=1.02467235254
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=14 (PA offset=-90.0deg) q=0.286595005512 u=0.248268081647 p=0.379175075063 x=20.4506681683 Gx/Gy=1.42319096734
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=15 (PA offset=-90.0deg) q=0.269695669847 u=0.238296710599 p=0.359890367497 x=20.7315265817 Gx/Gy=1.36916041149
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=16 (PA offset=-90.0deg) q=0.232111837329 u=0.208660907513 p=0.312114208828 x=20.9772497111 Gx/Gy=1.26992484854
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=17 (PA offset=-90.0deg) q=0.206416896105 u=0.179306963666 p=0.273420778685 x=20.4898383003 Gx/Gy=1.2150621135
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=18 (PA offset=-90.0deg) q=0.238704411296 u=0.207126091047 p=0.316039575947 x=20.4742437774 Gx/Gy=1.27906703553
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=19 (PA offset=-90.0deg) q=0.2416252955 u=0.213763470155 p=0.322610608316 x=20.7494324703 Gx/Gy=1.29006007015
# 2022-03-29 08:12:56	INFO	polfromgain::::	Fld=J0137+3309 Spw=0 Ant=20 (PA offset=-90.0deg) q=0.232896576945 u=0.216804183744 p=0.318189989851 x=21.4752819756 Gx/Gy=1.28303072236
# 2022-03-29 08:12:56	SEVERE	polfromgain::::	Task polfromgain raised an exception of class ValueError with the following message: math domain error
# Running CASA task 'polfromgain'
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 10, in <module>
#     task.run()
#   File "/usr/local/lib/python3.8/dist-packages/Crasa/Crasa.py", line 122, in run
#     raise CasaException("CASA raised a SEVERE exception while running task {0:s}".format(self.task))
# Crasa.Crasa.CasaException: CASA raised a SEVERE exception while running task polfromgain
2022-03-29 10:12:56 CARACal.Stimela.QU_from_gain ERROR: cd /mnt/12tb/merghers/epoch4b/.stimela_workdir-1648539981682496 && singularity returns error code 1
2022-03-29 10:12:56 CARACal.Stimela.QU_from_gain ERROR: job failed at 2022-03-29 10:12:56.664718 after 0:00:10.151649
2022-03-29 10:12:56 CARACal ERROR: Job 'QU_from_gain' failed: cd /mnt/12tb/merghers/epoch4b/.stimela_workdir-1648539981682496 && singularity returns error code 1 [PipelineException]
2022-03-29 10:12:56 CARACal INFO:   More information can be found in the logfile at output/logs-20220329-094618/log-caracal.txt
2022-03-29 10:12:56 CARACal INFO: exiting with error code 1

Using a smaller bandwidth hasn't solved it.

**Comment by francescaLoi** [comment]
can you show the elevation plot? It is created by CARACal at the beginning of the run and saved in the msdir

**Comment by Sinenhlanhla** [comment]
@francescaLoi I've attached the plot here
![cfp2020_4b-elevation-tracks](https://user-images.githubusercontent.com/20106975/161729414-adf31837-9d44-49c0-907e-3ac31b7a7004.png)
