### ISSUE TITLE
Non-standard flux calibrators

### ISSUE THREAD

**Issue by rstofi** [caracal-pipeline/caracal#1436]
Hi, I am working with some unusual MS in which I have only a single calibrator source that I use as a primary (and secondary) calibrator

**Comment by o-smirnov** [comment]
Come to think of it, 3C273 is a pretty shitty calibrator for MeerKAT since we should resolve it nicely. But still, if it's in the standard CASA list, Caracal should pick it up and use it without complaint. @paoloserra @gigjozsa any ideas?

**Comment by KshitijT** [comment]
@rstofi , I couldn't find 3C273 in the CASA flux calibrator database; it's definitely possible that while it's good enough for a gain calibrator, the flux density of 3C273 is variable at higher frequencies at least and thus it does not figure in the CASA flux calibrator database? Please correct me if I am wrong.

So to get around that, what I have done is the following: I have added a custom model of 3C273 taken from VLA observations (specifically CASA pipeline flux density mining) : http://www.vla.nrao.edu/astro/calib/vlacal/cal_mon/last/1229+0203.html and in the branch `quickfix_issue1436`. Could you please install caracal from that branch? 

Assuming your observations are L-band, you should get a flux density of 32-ish Jy for the 3C273. 

I haven't been able to test it extensively, so please let me know in case this doesn't work for some reason.

**Comment by rstofi** [comment]
@KshitijT thanks for the quick fix, I will test it and get back to you if I have any issues!

**Comment by rstofi** [comment]
@KshitijT  I managed to run the installation of the custom branch, and I ran into the following error:
```
2022-07-29 16:01:22 CARACal INFO: prep: initializing
2022-07-29 16:01:22 CARACal INFO: Obtaining divine knowledge from /users/krozgonyi/image_AT2017_wk/custom_caracal_3C273/lib/python3.8/site-packages/caracal/data/southern_calibrators.txt
2022-07-29 16:01:22 CARACal ERROR: Illegal line encountered while parsingsouthern standard at line 43:'name=3C273    epoch=2022 ra=12h29m06.6s dec=+02d03m08s a=5.90891 b=-0.55714 c=0.03639 d=0.0 
' [RuntimeError]
2022-07-29 16:01:22 CARACal INFO:   More information can be found in the logfile at /idia/users/krozgonyi/AT2017_wk/cal_3C273_1556052116/output/logs-20220729-155042/log-caracal.txt
2022-07-29 16:01:22 CARACal INFO:   You are running version 1.0.6
2022-07-29 16:01:23 CARACal ERROR: Traceback (most recent call last):
2022-07-29 16:01:23 CARACal ERROR:   File "/users/krozgonyi/image_AT2017_wk/custom_caracal_3C273/lib/python3.8/site-packages/caracal/main.py", line 187, in __run
2022-07-29 16:01:23 CARACal ERROR:     pipeline.run_workers()
2022-07-29 16:01:23 CARACal ERROR:   File "/users/krozgonyi/image_AT2017_wk/custom_caracal_3C273/lib/python3.8/site-packages/caracal/workers/worker_administrator.py", line 441, in run_workers
2022-07-29 16:01:23 CARACal ERROR:     worker.worker(self, recipe, config)
2022-07-29 16:01:23 CARACal ERROR:   File "/users/krozgonyi/image_AT2017_wk/custom_caracal_3C273/lib/python3.8/site-packages/caracal/workers/prep_worker.py", line 69, in worker
2022-07-29 16:01:23 CARACal ERROR:     db = mkct.calibrator_database()
2022-07-29 16:01:23 CARACal ERROR:   File "/users/krozgonyi/image_AT2017_wk/custom_caracal_3C273/lib/python3.8/site-packages/caracal/dispatch_crew/caltables.py", line 28, in calibrator_database
2022-07-29 16:01:23 CARACal ERROR:     __CALIBRATOR_DB = cp.catalog_parser(__DB_FILENAME)
2022-07-29 16:01:23 CARACal ERROR:   File "/users/krozgonyi/image_AT2017_wk/custom_caracal_3C273/lib/python3.8/site-packages/caracal/dispatch_crew/catalog_parser.py", line 14, in __init__
2022-07-29 16:01:23 CARACal ERROR:     self._cat = cls.read_caltable(filename)
2022-07-29 16:01:23 CARACal ERROR:   File "/users/krozgonyi/image_AT2017_wk/custom_caracal_3C273/lib/python3.8/site-packages/caracal/dispatch_crew/catalog_parser.py", line 103, in read_caltable
2022-07-29 16:01:23 CARACal ERROR:     raise RuntimeError("Illegal line encountered while parsing"
2022-07-29 16:01:23 CARACal ERROR: RuntimeError: Illegal line encountered while parsingsouthern standard at line 43:'name=3C273    epoch=2022 ra=12h29m06.6s dec=+02d03m08s a=5.90891 b=-0.55714 c=0.03639 d=0.0 
2022-07-29 16:01:23 CARACal ERROR: '
2022-07-29 16:01:23 CARACal INFO: exiting with error code 1
```

**Comment by KshitijT** [comment]
Hmmmm, weird, let me take a look. It's probably some tab or something.

**Comment by KshitijT** [comment]
@rstofi , I think I have fixed the issue; could you please re-pull the branch?

**Comment by rstofi** [comment]
It is working, but when I make a dirty image of the calibrator, I measure ~3235 Jy peak flux, and my target field images are messed up too. I wonder if the two are related...  I will do some double-checking of my imaging parameters and get back to you!

**Comment by KshitijT** [comment]
@rstofi I have fixed the 3k Jy flux issue, I think - please repull from the branch and see if you get the correct flux (just re-running crosscal should do it, I think). About the target images being messed up - I am not sure they are related, but please do check if that improves too.

**Comment by KshitijT** [comment]
@rstofi , could you confirm if this is sorted now ?

**Comment by KshitijT** [comment]
Closing this, reopen if needed.
