### ISSUE TITLE
Error in line worker

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#1452]
Hi,

I am getting following error in ``wsclean`` run in the ``line`` worker 
```
# + + + + + + + + + + + + + + + + + + +
# + An exception occured:
# + >>> RegularFileIO: error in open or create of file /stimela_mount/msdir/NGC1512_raw_data2-NGC1512-corr_mst.ms/table.dat: Too many open files
# + + + + + + + + + + + + + + + + + + +
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 69, in <module>
#     subprocess.check_call(shlex.split(_runc))
#   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
#     raise CalledProcessError(retcode, cmd)
```
It's working with only few 100 channels but failing when using all channels. 
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/9890534/log-caracal.txt)

**Comment by paoloserra** [comment]
Can you check whether this is the same problem as in #998? See `ulimit`.

See also #1414

**Comment by paoloserra** [comment]
Did this work?

**Comment by paoloserra** [comment]
@viralp can we close this?

**Comment by viralp** [comment]
Yes
