### ISSUE TITLE
Error in Sofia

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#1453]
Hi

I am getting the following error in Sofia

```
CARACal ERROR: stimela.exceptions.PipelineException: Job 'sofia-source_finding-58:: Make SoFiA mask and images for cube output/cubes/mypipelinerun_NGC1512_HI_1-0039-image.fits' failed: cd /vault-ike/parekh/ngc15122/.stimela_workdir-16670689199661515 && singularity run --workdir /vault-ike/parekh/ngc15122/.stimela_workdir-16670689199661515 --containall returns error code 1
```
The slice (```mypipelinerun_NGC1512_HI_1-0039-image.fits```) where it complaining has all zero values. How to avoid this slice in the pipeline run?
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/9911914/log-caracal.txt)

**Comment by paoloserra** [comment]
Not sure how we can help here (relevant error below). If it is a bug, it is a bug in SoFiA-1, which is no longer maintained -- see https://github.com/SoFiA-Admin/SoFiA .

We're currently in the process of switching to SoFiA-2 within CARACal. In the meantime, maybe you could consider running SoFiA-2 stand-alone outside CARACal?

```
# --- SoFiA 1.3.2: Writing moment maps -----------------------------------------
#     Elapsed time: 00:00:02.45 h
# 
# Writing moment-0
# Writing moment-1
# /sofia/sofia_pipeline.py:695: RuntimeWarning: All-NaN slice encountered
#   writemoment2.writeMoments(np_Cube, mask, outroot, debug, dict_Header, Parameters["writeCat"]["compress"], write_mom[0], write_mom[1], Parameters["writeCat"]["overwrite"])
# Traceback (most recent call last):
#   File "/sofia/sofia_pipeline.py", line 695, in <module>
#     writemoment2.writeMoments(np_Cube, mask, outroot, debug, dict_Header, Parameters["writeCat"]["compress"], write_mom[0], write_mom[1], Parameters["writeCat"]["overwrite"])
#   File "writemoment2.pyx", line 212, in writemoment2.writeMoments
#   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/header.py", line 194, in __setitem__
#     self._update((key, value, comment))
#   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/header.py", line 1632, in _update
#     self.append(card)
#   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/header.py", line 1164, in append
#     card = Card(*card)
#   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/card.py", line 192, in __init__
#     self.value = value
#   File "/usr/local/lib/python2.7/dist-packages/astropy/io/fits/card.py", line 315, in value
#     "in FITS headers.".format(value))
# ValueError: Floating point nan values are not allowed in FITS headers.
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 61, in <module>
#     subprocess.check_call(shlex.split(_runc))
#   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['sofia_pipeline.py', 'sofia_parameters.par']' returned non-zero exit status 1
```

**Comment by Athanaseus** [comment]
Fixed in SOFIA2, and still to implement the updates in caracal.

**Comment by paoloserra** [comment]
... well, not necessarily fixed in SoFiA-2, but the suggestion was to try SoFiA-2 and report indeed ... :)
