### ISSUE TITLE
Default GSL error handler invoked

### ISSUE THREAD

**Issue by ianjarog** [caracal-pipeline/caracal#1499]
Hi all, 
Anybody knows how to solve this: 

# Default GSL error handler invoked.
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 69, in <module>
#     subprocess.check_call(shlex.split(_runc))
#   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['wsclean', '-name', '/stimela_mount/output/continuum/image_4/g1663716690_ep1_32_NGC300_p01_4', '-j', '28', '-mem', '100', '-absmem', '50.0', '-weight', 'briggs', '0.0', '-no-mfs-weighting', '-size', '5400', '5400', '-scale', '1.0asec', '-channels-out', '3', '-nwlayers-factor', '3', '-pol', 'I', '-data-column', 'CORRECTED_DATA', '-niter', '1000000', '-auto-threshold', '0.5', '-auto-mask', '5.0', '-gain', '0.1', '-mgain', '0.9', '-join-channels', '-fit-spectral-pol', '2', '-padding', '1.3', '-save-source-list', '/stimela_mount/msdir/1663716690_sdp_l0_full_rdb_ep1_32-NGC300_p01-corrfreqavg.ms']' died with <Signals.SIGABRT: 6>.
2023-04-16 20:29:39 CARACal.Stimela.image-field1-iter4 ERROR: cd /net/sinatra/vault2-ike/ianja/MeerKAT_IANJA/.stimela_workdir-16816598622922873 && singularity run --workdir /net/sinatra/vault2-ike/ianja/MeerKAT_IANJA/.stimela_workdir-16816598622922873 --containall returns error code 1
2023-04-16 20:29:39 CARACal.Stimela.image-field1-iter4 ERROR: job failed at 2023-04-16 20:29:39.873538 after 0:01:48.479176
2023-04-16 20:29:39 CARACal ERROR: Job 'image-field1-iter4:: Make wsclean image (selfcal iter 4)' failed: cd /net/sinatra/vault2-ike/ianja/MeerKAT_IANJA/.stimela_workdir-16816598622922873 && singularity run --workdir /net/sinatra/vault2-ike/ianja/MeerKAT_IANJA/.stimela_workdir-16816598622922873 --containall returns error code 1 [PipelineException]
2023-04-16 20:29:39 CARACal INFO:   More information can be found in the logfile at ./g1663716690_ep1_32_OUT//logs-20230416-174420/log-caracal.txt
2023-04-16 20:29:39 CARACal INFO: exiting with error code 1

**Comment by Athanaseus** [comment]
Could you let me know if you are still having this issue with the latest release?
