### ISSUE TITLE
Target name not accepted by ddcal worker

### ISSUE THREAD

**Issue by Dakalo12** [caracal-pipeline/caracal#1548]
The ddcal worker is not accepting the target name. It replaces an underscore with a dash, then gives the KeyError.

Output from the log file: 

# INFO:    Converting SIF file to temporary sandbox...
# INFO:    Cleaning up image...
2023-11-05 21:19:10 CARACal.Stimela.ddf_image-J1142_7_p_1527 INFO: job complete at 2023-11-05 21:19:10.322475 after 6:39:05.129036
2023-11-05 21:19:10 CARACal.Stimela.ddcal INFO: Saving pipeline information in .last_ddcal.json
2023-11-05 21:19:10 CARACal.Stimela.ddcal INFO: Recipe executed successfully
2023-11-05 21:19:10 CARACal ERROR: 'J1142_7_p_1527' [KeyError]
2023-11-05 21:19:10 CARACal INFO:   More information can be found in the logfile at output/logs-20231105-071940/log-caracal.txt
2023-11-05 21:19:10 CARACal INFO:   You are running version 1.0.6-479-g51b1efd1
2023-11-05 21:19:10 CARACal ERROR: Traceback (most recent call last):
2023-11-05 21:19:10 CARACal ERROR:   File "/scratch3/users/dakalo/caracal/caracal/caracal/main.py", line 189, in __run
2023-11-05 21:19:10 CARACal ERROR:     pipeline.run_workers()
2023-11-05 21:19:10 CARACal ERROR:   File "/scratch3/users/dakalo/caracal/caracal/caracal/workers/worker_administrator.py", line 436, in run_workers
2023-11-05 21:19:10 CARACal ERROR:     worker.worker(self, recipe, config)
2023-11-05 21:19:10 CARACal ERROR:   File "/scratch3/users/dakalo/caracal/caracal/caracal/utils/requires.py", line 25, in inner_func
2023-11-05 21:19:10 CARACal ERROR:     return func(*args, **kw)
2023-11-05 21:19:10 CARACal ERROR:   File "/scratch3/users/dakalo/caracal/caracal/caracal/workers/ddcal_worker.py", line 431, in worker
2023-11-05 21:19:10 CARACal ERROR:     dagga(field)
2023-11-05 21:19:10 CARACal ERROR:   File "/scratch3/users/dakalo/caracal/caracal/caracal/workers/ddcal_worker.py", line 249, in dagga
2023-11-05 21:19:10 CARACal ERROR:     sources_to_tag = de_dict[field.replace("_", "-")]
2023-11-05 21:19:10 CARACal ERROR: KeyError: 'J1142_7_p_1527'
2023-11-05 21:19:10 CARACal INFO: exiting with error code 1

[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/13280782/log-caracal.txt)

**Comment by KshitijT** [comment]
@Dakalo12 this is a known issue, unfortunately. The bug is being fixed, but a quicker solution to save time is to just change the field name in the MS file and rerun.

**Comment by Dakalo12** [comment]
@KshitijT I am a beginner in data reduction, so I do not know how to edit the field name in the MS file. May you please guide me on how to go about it?
