### ISSUE TITLE
Adding the J0137+3309 polcal model

### ISSUE THREAD

**Issue by Sinenhlanhla** [caracal-pipeline/caracal#1551]
Would it be possible to add J0137+3309 to the known polarisation calibrators? The MeerKAT_Calibrator_Project (
[MeerKAT_Calibrator_Project.pdf](https://github.com/caracal-pipeline/caracal/files/13424647/MeerKAT_Calibrator_Project.pdf)
) documentation has the model information for this source.

**Comment by francescaLoi** [comment]
Hi @Sinenhlanhla , I just pushed a new branch (issue1551) with the calibrator properties. Can you try it and let me know?

**Comment by Sinenhlanhla** [comment]
Hi @francescaLoi, how did you label the branch? When I try to checkout, I get the following error
`error: pathspec 'issue1551' did not match any file(s) known to git`
I also tried 'issue-1551'

**Comment by francescaLoi** [comment]
It's there: [issue1551](https://github.com/caracal-pipeline/caracal/tree/issue1551)

**Comment by Sinenhlanhla** [comment]
@francescaLoi 
Even after moving to the branch
`Your branch is up to date with 'origin/issue1551'`
I get this error:
`2024-02-02 14:59:47 CARACal ERROR: Unable to determine pol_calib=xcal. Is your obsconf section configured properly?Your setting of pol_calib=xcal selects J0137+3309.
                                    Supported calibrators are 3C138, 3C286, J1130-1449, J1331+3030, J0521+1638.
                                    Alternatively, you can calibrate both leakage and polarization using a (known or unknown) polarized source
                    observed at several parallactic angles. Configure this source as obsconf:xcal, and leakage_calib=pol_calib=xcal. [RuntimeError]`

**Comment by Sinenhlanhla** [comment]
@francescaLoi Thanks, the model has been successfully added. 
However, I am now getting the below error
`2024-04-16 12:28:27 CARACal ERROR: Job 'crosshand_phase_ref' failed: /software/common/singularity/3.11.3/bin/singularity run --workdir /scratch3/users/precious/merg-t1/epoch5a/.stimela_workdir-17132595995172687 --containall --userns returns error code 1 [PipelineException]
2024-04-16 12:28:27 CARACal INFO:   More information can be found in the logfile at output/logs-20240416-112617/log-caracal.txt
2024-04-16 12:28:27 CARACal INFO:   You are running version 1.0.6-517-g0d594e7d
2024-04-16 12:28:28 CARACal ERROR: Traceback (most recent call last):
2024-04-16 12:28:28 CARACal ERROR:   File "/scratch3/users/precious/merg-t1/caracal/caracal/main.py", line 189, in __run
2024-04-16 12:28:28 CARACal ERROR:     pipeline.run_workers()
2024-04-16 12:28:28 CARACal ERROR:   File "/scratch3/users/precious/merg-t1/caracal/caracal/workers/worker_administrator.py", line 436, in run_workers
2024-04-16 12:28:28 CARACal ERROR:     worker.worker(self, recipe, config)
2024-04-16 12:28:28 CARACal ERROR:   File "/scratch3/users/precious/merg-t1/caracal/caracal/workers/polcal_worker.py", line 1353, in worker
2024-04-16 12:28:28 CARACal ERROR:     xcal_model_fcal_leak(msname, msinfo, prefix_msbase, recipe, config, pipeline, i, prefix, refant, polarized_calibrators,
2024-04-16 12:28:28 CARACal ERROR:   File "/scratch3/users/precious/merg-t1/caracal/caracal/workers/polcal_worker.py", line 303, in xcal_model_fcal_leak
2024-04-16 12:28:28 CARACal ERROR:     recipe.run()
2024-04-16 12:28:28 CARACal ERROR:   File "/scratch3/users/precious/merg-t1/venv-caracal/lib/python3.9/site-packages/stimela/recipe.py", line 764, in run
2024-04-16 12:28:28 CARACal ERROR:     raise PipelineException(exc, self.completed, job, self.remaining) from None
2024-04-16 12:28:28 CARACal ERROR: stimela.exceptions.PipelineException: Job 'crosshand_phase_ref' failed: /software/common/singularity/3.11.3/bin/singularity run --workdir /scratch3/users/precious/merg-t1/epoch5a/.stimela_workdir-17132595995172687 --containall --userns returns error code 1
2024-04-16 12:28:28 CARACal INFO: exiting with error code 1`

**Comment by francescaLoi** [comment]
Hi Precious,
can you attach the log?

**Comment by Sinenhlanhla** [comment]
Hi Francesca.
I've attached it below.
[log-caracal.txt](https://github.com/caracal-pipeline/caracal/files/15027019/log-caracal.txt)

**Comment by francescaLoi** [comment]
It seems that there is no data between 1005 and 1255 MHz. Maybe these frequency range was flagged? Please check your data.

**Comment by francescaLoi** [comment]
Hi @Sinenhlanhla , I am going to close the issue since it is now fixed.
Please, refer to the `polimager` branch to load the model by Taylor&Legodi 2024. The syntax for the polcal worker is now:
```
polcal:
  enable: true
  label_in: cal
  label_cal: 1pcal
  otfcal:
    enable: true
    label_cal: 1kgb
  extendflags: true
  feed_angle_rotation: '-90'
  uvrange: '>150'
  reuse_existing_tables: false
  pol_calib: xcal
  leakage_calib: fcal
  set_model_pol:
    enable: true
    nrao_model: false
    taylor_legodi_model: true
  gain_solint: '60s'
  time_solint: 'inf'
  plotgains: true
  apply_pcal: true
  applyto:
    - gcal
    - bpcal
    - xcal
```
