### ISSUE TITLE
Failed to create user namespace: user namespace disabled

### ISSUE THREAD

**Issue by arpan-52** [caracal-pipeline/caracal#1567]
Let me first describe the setup.
1. I have made a python 3.8 virtual environment with Anaconda.
2. Installed singularity with conda, version 3.8.6
3. Installed Stimela version 1.7.9 with Conda.
4. I have also specified the path for the singularity cache and temp directories. 
5. After pulling all the images with singularity I tried to run my .yml file. 
6. Whatever I am trying to do I am getting an error..

The error.....

# INFO:    Converting SIF file to temporary sandbox...

# FATAL:   while extracting /data/manisha/TEST_DATA/arpan/STIMELA_IMAGES/stimela_ddfacet_1.7.1.sif: root filesystem extraction failed: extract command failed: ERROR  : Failed to create user namespace: user namespace disabled
# : exit status 1
2024-01-23 15:53:31 STIMELA.image_target_1 ERROR: /data/manisha/TEST_DATA/arpan/anaconda3/envs/38data/bin/singularity run --workdir /data/manisha/TEST_DATA/arpan/test_caracal/.stimela_workdir-17060054084448693 --containall --userns returns error code 255
2024-01-23 15:53:31 STIMELA.image_target_1 ERROR: job failed at 2024-01-23 15:53:31.281294 after 0:00:01.924652
2024-01-23 15:53:31 STIMELA.image_target_1 ERROR: Traceback (most recent call last):
2024-01-23 15:53:31 STIMELA.image_target_1 ERROR:   File "/data/manisha/TEST_DATA/arpan/anaconda3/envs/38data/lib/python3.8/site-packages/stimela/recipe.py", line 713, in run
2024-01-23 15:53:31 STIMELA.image_target_1 ERROR:     job.run_job()
2024-01-23 15:53:31 STIMELA.image_target_1 ERROR:   File "/data/manisha/TEST_DATA/arpan/anaconda3/envs/38data/lib/python3.8/site-packages/stimela/recipe.py", line 425, in run_job
2024-01-23 15:53:31 STIMELA.image_target_1 ERROR:     self.job.run(output_wrangler=self.apply_output_wranglers)
2024-01-23 15:53:31 STIMELA.image_target_1 ERROR:   File "/data/manisha/TEST_DATA/arpan/anaconda3/envs/38data/lib/python3.8/site-packages/stimela/singularity.py", line 128, in run
2024-01-23 15:53:31 STIMELA.image_target_1 ERROR:     utils.xrun(f"{BINARY} run --workdir {self.execdir} --containall {extras}",
2024-01-23 15:53:31 STIMELA.image_target_1 ERROR:   File "/data/manisha/TEST_DATA/arpan/anaconda3/envs/38data/lib/python3.8/site-packages/stimela/utils/xrun_poll.py", line 227, in xrun
2024-01-23 15:53:31 STIMELA.image_target_1 ERROR:     raise StimelaCabRuntimeError("{} returns error code {}".format(command_name, status))
2024-01-23 15:53:31 STIMELA.image_target_1 ERROR: stimela.utils.StimelaCabRuntimeError: /data/manisha/TEST_DATA/arpan/anaconda3/envs/38data/bin/singularity run --workdir /data/manisha/TEST_DATA/arpan/test_caracal/.stimela_workdir-17060054084448693 --containall --userns returns error code 255
2024-01-23 15:53:

From the initial inspection, it looks to me as a singularity problem. Is not conda installed singularity sufficient? Do we need a singularity with root permissions?

**Comment by KshitijT** [comment]
This seems similar to #1532. @arpan-52 do you permissions to pull the singularity images on the machine you are using?

**Comment by arpan-52** [comment]
I have used

 stimela run ddf_stimela_hogbom_mask.py

This .py file contains all the recipes to do the imaging.

**Comment by KshitijT** [comment]
@arpan-52 this is a stimela issue, not a CARACal one, could you please close this issue and open it on the stimela repository?

**Comment by arpan-52** [comment]
Hi, I finally managed to tackle the issue with a system-wide updated version of singularity installation. The issue is now gone and the whole code works well. Thanks a lot.
