### ISSUE TITLE
Outdated instructions

### ISSUE THREAD

**Issue by KarinaSantana** [caracal-pipeline/caracal#1602]
I tried to install it using the README file. This command: pip install -U caracal[all] did not work. This is the error I got:

` zsh: no matches found: caracal[all]`

When trying the same command on bash I got the follow error: 

```
Collecting PyYAML>=3.13 (from astropy<6.0.0,>=5.2.2->caracal[all])
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/karinasantana/car_venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/karinasantana/car_venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/karinasantana/car_venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 311, in run
          self.find_sources()
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 319, in find_sources
          mm.run()
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 540, in run
          self.add_defaults()
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 108, in add_defaults
          super().add_defaults()
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 238, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 323, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/rl/2qhyvn_946jdpnhqs1ttcnbh0000gn/T/pip-build-env-i6e_meug/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(car_venv) %n@%m %1~ %#
```

Note: It is also not clear if caracal can be installed on mac with intel chip

**Comment by KshitijT** [comment]
@KarinaSantana , could you please attach the script / commands you used for the bash case?

**Comment by KarinaSantana** [comment]
Hi Kshitij

here you go:
'''
(car_venv) ***@***.*** ~ % bash

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(car_venv) %n@%m %1~ %# pip install -U caracal[all]
Collecting caracal[all]

'''

**Comment by JSKenyon** [comment]
Try "caracal[all]" in string quotes. Zsh has special handling for square
brackets.

**Comment by Athanaseus** [comment]
Hi @KarinaSantana , thanks for opening this issue.
Sorry, we have not fully tested the pipeline in a `python3.12` environment yet.
I have updated the readme in this PR:  https://github.com/caracal-pipeline/caracal/pull/1603
Please re-install using the branch with: ` pip install "caracal[all] @ git+https://github.com/caracal-pipeline/caracal.git@update-docs -U"`
NB: This should fix this in the next release of `caracal`.

Regarding mac please refer to: https://github.com/caracal-pipeline/caracal/issues/1346.

I hope this helps.

Best regards

**Comment by KshitijT** [comment]
Hey @KarinaSantana , just to add to what @Athanaseus said - I checked your install process with different python versions and it's the 3.12 which gives the trouble, 3.08 works fine.
