### ISSUE TITLE
aoflagger fails with 'ascii' codec error

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#542]
Trying plan (b) from https://github.com/ska-sa/meerkathi/issues/535#issuecomment-509362118, I am now thwarted by a new aoflagger error:
```
meerkathi - 2019-07-09 12:55:29,157 INFO -  executing: sh
meerkathi - 2019-07-09 12:55:29,158 INFO - Running: aoflagger -strategy /scratch/input/GMRT_GSB_First_Pass.rfis -indirect-read  -auto-read-mode  -c
olumn DATA -fields 2,6 /scratch/msdir/1557766852_sdp_l0_1284.hh_vv.ms
meerkathi - 2019-07-09 12:55:29,158 INFO - Traceback (most recent call last):
meerkathi - 2019-07-09 12:55:29,158 INFO -   File "/scratch/code/run.py", line 35, in <module>
meerkathi - 2019-07-09 12:55:29,158 INFO -     utils.xrun(cab['binary'], args+[msname])
meerkathi - 2019-07-09 12:55:29,158 INFO -   File "/scratch/stimela/utils/__init__.py", line 108, in xrun
meerkathi - 2019-07-09 12:55:29,158 INFO -     _print_info(fout.read())
meerkathi - 2019-07-09 12:55:29,159 INFO -   File "/scratch/stimela/utils/__init__.py", line 62, in _print_info
meerkathi - 2019-07-09 12:55:29,159 INFO -     msg = msg.encode("utf-8")
meerkathi - 2019-07-09 12:55:29,159 INFO - UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 193: ordinal not in range(128)
```
Guessing it's to do with @SpheMakh's unicode support changes last week?

**Comment by AstroRipples** [comment]
Well, it's been nearly two years, and I can't tell if this has come back again, but at the flagging step of `CARACal`, I'm getting a shockingly similar error to that encountered by @o-smirnov : 

```
2021-05-15 13:46:56 CARACal.Stimela.init_ws-ms0 INFO: job complete at 2021-05-15 13:46:56.475659 after 0:00:28.606065
2021-05-15 13:46:56 CARACal.Stimela.prep INFO: Saving pipeline information in .last_prep.json
2021-05-15 13:46:56 CARACal.Stimela.prep INFO: Recipe executed successfully
2021-05-15 13:46:56 CARACal INFO: prep: finished
2021-05-15 13:46:56 CARACal.Stimela.flag INFO: ---------------------------------
2021-05-15 13:46:56 CARACal.Stimela.flag INFO: Stimela version 1.6.9
2021-05-15 13:46:56 CARACal.Stimela.flag INFO: Running: flag
2021-05-15 13:46:56 CARACal.Stimela.flag INFO: ---------------------------------
2021-05-15 13:46:56 CARACal.Stimela.flag INFO: Config directory cannot be found. Will create /local/work/riseley/MeerKAT/ZwCl1454/.stimela_workdir-16210792164774098/stimela_parameter_files
2021-05-15 13:46:56 CARACal INFO: flag: initializing
2021-05-15 13:46:56 CARACal.Stimela.flag INFO: Adding cab '/local/work/riseley/MeerKAT/ZwCl1454/stimela_casa_1.6.3.sif' (5.6.1-8) to recipe, container name 'save-PipelineRun_Version0_flag_before-ms0'
2021-05-15 13:46:56 CARACal.Stimela.flag INFO: Adding cab '/local/work/riseley/MeerKAT/ZwCl1454/stimela_rfimasker_1.7.0.sif' (x.x.x) to recipe, container name 'flag-mask-ms0'
2021-05-15 13:46:56 CARACal ERROR: 'ascii' codec can't decode byte 0xc3 in position 120: ordinal not in range(128) [UnicodeDecodeError]
2021-05-15 13:46:56 CARACal INFO:   More information can be found in the logfile at OutputData/logs-20210515-134315/log-caracal.txt
2021-05-15 13:46:56 CARACal INFO:   You are running version 1.0.4
2021-05-15 13:46:56 CARACal ERROR: Traceback (most recent call last):
2021-05-15 13:46:56 CARACal ERROR:   File "/homes/riseley/caracal/lib/python3.6/site-packages/caracal/main.py", line 183, in __run
2021-05-15 13:46:56 CARACal ERROR:     pipeline.run_workers()
2021-05-15 13:46:56 CARACal ERROR:   File "/homes/riseley/caracal/lib/python3.6/site-packages/caracal/workers/worker_administrator.py", line 413, in run_workers
2021-05-15 13:46:56 CARACal ERROR:     worker.worker(self, recipe, config)
2021-05-15 13:46:56 CARACal ERROR:   File "/homes/riseley/caracal/lib/python3.6/site-packages/caracal/workers/flag_worker.py", line 401, in worker
2021-05-15 13:46:56 CARACal ERROR:     for ss in stdr.readlines():
2021-05-15 13:46:56 CARACal ERROR:   File "/homes/riseley/caracal/lib64/python3.6/encodings/ascii.py", line 26, in decode
2021-05-15 13:46:56 CARACal ERROR:     return codecs.ascii_decode(input, self.errors)[0]
2021-05-15 13:46:56 CARACal ERROR: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 120: ordinal not in range(128)
2021-05-15 13:46:56 CARACal INFO: exiting with error code 1
```

Though I don't see any mention of `aoflagger` so perhaps not... The inputs I'm using for `flag` are modified versions of the pipeline `yml` file defaults: 

```
flag:
  enable: true
  field: calibrators
  label_in: cal
  flag_autocorr:
    enable: false
  flag_spw:
    enable: false
    chans: '0:856~880MHz , 0:1658~1800MHz, 0:1419.8~1421.3MHz'
    ensure_valid: false
  flag_mask:
    enable: true
    mask: meerkat.rfimask.npy
    uvrange: '0~1000'
  flag_rfi:
    enable: true
    flagger: aoflagger
    aoflagger:
      strategy: firstpass_QUV.rfis
```

So it _looks_ from the output like it's probably failing at the `flag_mask` step. Is there something iffy in the `meerkat.rfimask.npy` file that's the problem?

**Comment by KshitijT** [comment]
@AstroRipples , could you try using tricolour instead? The flagging section would look like this:

```
flag:
  enable: true
  field: calibrators
  label_in: cal
  flag_autocorr:
    enable: false
  flag_spw:
    enable: false
    chans: '*:856~880MHz , *:1658~1800MHz, *:1419.8~1421.3MHz'
    ensure_valid: true
  flag_antennas:
    enable: false
    antennas: '0'
  flag_mask:
    enable: false
    mask: meerkat.rfimask.npy
    uvrange: '0~1000'
  flag_rfi:
    enable: true
    flagger: tricolour
    tricolour:
      strategy: mk_rfi_flagging_calibrator_fields_firstpass.yaml
```

No need to then worry about the rfimask - tricolour incorporates it.

**Comment by AstroRipples** [comment]
@KshitijT: legend, that's taken care of the issue 🎉
