### ISSUE TITLE
mysterious error message when config file has duplicate sections

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/caracal#633]
It's an easy mistake to make (copy-paste a section, forget to add "__2" at the end of its name), but the error message is very confusing:

```
(meerkathi) oms@young:~/projects/OldDevils$ meerkathi -c reobs2.yml
Traceback (most recent call last):
  File "/home/oms/.venv/meerkathi/bin/meerkathi", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/oms/projects/meerkathi/bin/meerkathi", line 4, in <module>
    import meerkathi.main as main
  File "/home/oms/projects/meerkathi/meerkathi/main.py", line 20, in <module>
    from meerkathi.view_controllers import event_loop
  File "/home/oms/projects/meerkathi/meerkathi/view_controllers/__init__.py", line 3, in <module>
    from meerkathi.view_controllers.entry_form import entry_form
  File "/home/oms/projects/meerkathi/meerkathi/view_controllers/entry_form.py", line 9, in <module>
    from meerkathi.view_controllers.option_editor import option_editor
  File "/home/oms/projects/meerkathi/meerkathi/view_controllers/option_editor.py", line 188, in <module>
    class option_editor(npyscreen.FormBaseNew):
  File "/home/oms/projects/meerkathi/meerkathi/view_controllers/option_editor.py", line 200, in option_editor
    def on_load(self, labeltype=npyscreen.TitleFilenameCombo, labeltext="Filename", editvalue=cp().args.config):
  File "/home/oms/projects/meerkathi/meerkathi/dispatch_crew/config_parser.py", line 289, in __init__
    f, ruamel.yaml.RoundTripLoader, version=(1, 1))
  File "/home/oms/.venv/meerkathi/lib/python3.6/site-packages/ruamel/yaml/main.py", line 949, in load
    return loader._constructor.get_single_data()
  File "/home/oms/.venv/meerkathi/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 113, in get_single_data
    return self.construct_document(node)
  File "/home/oms/.venv/meerkathi/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 123, in construct_document
    for _dummy in generator:
  File "/home/oms/.venv/meerkathi/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 1624, in construct_yaml_omap
    assert key not in omap
AssertionError
```

**Comment by paoloserra** [comment]
still not pretty

```
Traceback (most recent call last):
  File "/home/pserra/Astro/caracal_venv/lib/python3.5/site-packages/caracal/main.py", line 273, in main
    config, version = parser.validate_config(config_file)
  File "/home/pserra/Astro/caracal_venv/lib/python3.5/site-packages/caracal/dispatch_crew/config_parser.py", line 141, in validate_config
    config_content = ruamel.yaml.load(file, ruamel.yaml.RoundTripLoader, version=(1, 1))
  File "/home/pserra/Astro/caracal_venv/lib/python3.5/site-packages/ruamel/yaml/main.py", line 951, in load
    return loader._constructor.get_single_data()
  File "/home/pserra/Astro/caracal_venv/lib/python3.5/site-packages/ruamel/yaml/constructor.py", line 113, in get_single_data
    return self.construct_document(node)
  File "/home/pserra/Astro/caracal_venv/lib/python3.5/site-packages/ruamel/yaml/constructor.py", line 123, in construct_document
    for _dummy in generator:
  File "/home/pserra/Astro/caracal_venv/lib/python3.5/site-packages/ruamel/yaml/constructor.py", line 1563, in construct_yaml_map
    self.construct_mapping(node, data, deep=True)
  File "/home/pserra/Astro/caracal_venv/lib/python3.5/site-packages/ruamel/yaml/constructor.py", line 1470, in construct_mapping
    if self.check_mapping_key(node, key_node, maptyp, key, value):
  File "/home/pserra/Astro/caracal_venv/lib/python3.5/site-packages/ruamel/yaml/constructor.py", line 295, in check_mapping_key
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "short.yml", line 1, column 1
found duplicate key "getdata" with value "ordereddict([('dataid', ['gps1'])])" (original value: "ordereddict([('dataid', ['gps2'])])")
  in "short.yml", line 13, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.

2020-05-10 23:40:26 CARACal ERROR: Error parsing arguments or configuration: while constructing a mapping
  in "short.yml", line 1, column 1
found duplicate key "getdata" with value "ordereddict([('dataid', ['gps1'])])" (original value: "ordereddict([('dataid', ['gps2'])])")
  in "short.yml", line 13, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.
```

**Comment by o-smirnov** [comment]
Yah that's pretty ugly. Try the ``issue-633`` version. Not perfect but better.

The trouble is that this is not the only exception possible from YAML parsing, and it hasn't got any identifying marks. So I can catch it and print it, but not much else.
