### ISSUE TITLE
Clip mode flagging 

### ISSUE THREAD

**Issue by viralp** [caracal-pipeline/caracal#909]
Hello,

Is clip mode flagging in crosscal is depreciated in the newer version of meerkathi?

To check clipminmax option, I copied crosscal all options to the default configuration file, but getting the following error

Traceback (most recent call last):
  File "/home/parekh/menv3/bin/meerkathi", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/parekh/meerkathi/bin/meerkathi", line 4, in <module>
    import meerkathi.main as main
  File "/home/parekh/meerkathi/meerkathi/main.py", line 20, in <module>
    from meerkathi.view_controllers import event_loop
  File "/home/parekh/meerkathi/meerkathi/view_controllers/__init__.py", line 3, in <module>
    from meerkathi.view_controllers.entry_form import entry_form
  File "/home/parekh/meerkathi/meerkathi/view_controllers/entry_form.py", line 9, in <module>
    from meerkathi.view_controllers.option_editor import option_editor
  File "/home/parekh/meerkathi/meerkathi/view_controllers/option_editor.py", line 188, in <module>
    class option_editor(npyscreen.FormBaseNew):
  File "/home/parekh/meerkathi/meerkathi/view_controllers/option_editor.py", line 200, in option_editor
    def on_load(self, labeltype=npyscreen.TitleFilenameCombo, labeltext="Filename", editvalue=cp().args.config):
  File "/home/parekh/meerkathi/meerkathi/dispatch_crew/config_parser.py", line 303, in __init__
    f, ruamel.yaml.RoundTripLoader, version=(1, 1))
  File "/home/parekh/menv3/lib/python3.6/site-packages/ruamel/yaml/main.py", line 951, in load
    return loader._constructor.get_single_data()
  File "/home/parekh/menv3/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 111, in get_single_data
    node = self.composer.get_single_node()
  File "/home/parekh/menv3/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 78, in get_single_node
    document = self.compose_document()
  File "/home/parekh/menv3/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 101, in compose_document
    node = self.compose_node(None, None)
  File "/home/parekh/menv3/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/parekh/menv3/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 218, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/parekh/menv3/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/parekh/menv3/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 218, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/parekh/menv3/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/parekh/menv3/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 211, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "/home/parekh/menv3/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 140, in check_event
    self.current_event = self.state()
  File "/home/parekh/menv3/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 589, in parse_block_mapping_key
    token.start_mark,
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "default_full.yml", line 122, column 6
expected <block end>, but found '<scalar>'
  in "default_full.yml", line 128, column 8

[default_full.txt](https://github.com/ska-sa/meerkathi/files/4440919/default_full.txt)

**Comment by KshitijT** [comment]
I assume that this is sorted, if not, please reopen.
