### ISSUE TITLE
tricolour welcome message

### ISSUE THREAD

**Issue by paoloserra** [caracal-pipeline/caracal#997]
If you run tricolour you get this welcome. It ain't pretty. No crash, no  big deal, but maybe we can fix that.

```
2020-04-24 23:02:21 CARACal.Stimela.flagging-rfi-ms0 INFO: job started at 2020-04-24 23:02:21.148848
# f088c37a453bf6763685bf9f18a17d2df07f99ac7228034bce24e3d392ec7b96
# --- Logging error ---
# Traceback (most recent call last):
#   File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
#     stream.write(msg)
# UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 452: ordinal not in range(128)
# Call stack:
#   File "/usr/local/bin/tricolour", line 8, in <module>
#     sys.exit(main())
#   File "/usr/local/lib/python3.6/dist-packages/tricolour/apps/tricolour/app.py", line 258, in main
#     _main(args)
#   File "/usr/local/lib/python3.6/dist-packages/tricolour/apps/tricolour/app.py", line 264, in _main
#     log.info(banner())
# Message: "\n*******************************************************************************\n                  _______   _           _\n                 |__   __| (_)         | |\n                    | |_ __ _  ___ ___ | | ___  _   _ _ __\n                    | | '__| |/ __/ _ \\| |/ _ \\| | | | '__|\n                    | | |  | | (_| (_) | | (_) | |_| | |\n                    |_|_|  |_|\\___\\___/|_|\\___/ \\__,_|_|\n\nViva la r\xe9volution!\n"
# Arguments: ()
# tricolour - 2020-04-24 21:02:23,004 INFO -
# *******************************************************************************
#                   _______   _           _
#                  |__   __| (_)         | |
#                     | |_ __ _  ___ ___ | | ___  _   _ _ __
#                     | | '__| |/ __/ _ \| |/ _ \| | | | '__|
#                     | | |  | | (_| (_) | | (_) | |_| | |
#                     |_|_|  |_|\___\___/|_|\___/ \__,_|_|
# 
# Viva la r\xe9volution!
# 
# tricolour - 2020-04-24 21:02:23,005 INFO - Flagging on the DATA column
# tricolour.mask - 2020-04-24 21:02:23,006 INFO - Looking for static masks...
...
```

**Comment by paoloserra** [comment]
For the record, with Stimela 1.7.3 we still get the ugly logging error messages when starting tricolour.
